// generated by gocipe a113b3c3d9f0bc69a9636981154d6293fbd50d8eed8462b35778873cde989dae; DO NOT EDIT

package feedback

import "time"

// Feedback represents feedback from a visitor on a session
type Feedback struct {
	ID        *int64     `json:"id"`
	VisitorID *int64     `json:"visitor_id"`
	Reaction1 *string    `json:"reaction_1"`
	Reaction2 *string    `json:"reaction_2"`
	Reaction3 *string    `json:"reaction_3"`
	Reaction4 *string    `json:"reaction_4"`
	CreatedAt *time.Time `json:"created_at"`
}

// New returns an instance of Feedback
func New() *Feedback {
	return &Feedback{
		ID:        new(int64),
		VisitorID: new(int64),
		Reaction1: new(string),
		Reaction2: new(string),
		Reaction3: new(string),
		Reaction4: new(string),
		CreatedAt: new(time.Time),
	}
}
