// generated by gocipe 7a9000d6c7c4a975fa1ad9470a4ce01982a28eb73f76dde520a18fc9354f2521; DO NOT EDIT

package feedback

import "time"

// Feedback represents feedback from a visitor on a session
type Feedback struct {
	ID        *int64     `json:"id"`
	SessionID *string    `json:"session_id"`
	VisitorID *string    `json:"visitor_id"`
	Reaction1 *string    `json:"reaction_1"`
	Reaction2 *string    `json:"reaction_2"`
	Reaction3 *string    `json:"reaction_3"`
	Reaction4 *string    `json:"reaction_4"`
	CreatedAt *time.Time `json:"created_at"`
}

// New returns an instance of Feedback
func New() *Feedback {
	return &Feedback{
		ID:        new(int64),
		SessionID: new(string),
		VisitorID: new(string),
		Reaction1: new(string),
		Reaction2: new(string),
		Reaction3: new(string),
		Reaction4: new(string),
		CreatedAt: new(time.Time),
	}
}
