// generated by gocipe; DO NOT EDIT

package main

import (
	"flag"
	"fmt"
	"github.com/gorilla/mux"
	"net/http"
	"os"
)

// Version info
var (
	appVersion = "n/a"
	appCommit  = "n/a"
	appBuilt   = "n/a"
)

func main() {
	version := flag.Bool("v", false, "prints current app version")
	flag.Parse()
	if *version {
		fmt.Printf("Version: %s \nCommit: %s \nBuilt: %s", appVersion, appCommit, appBuilt)
		os.Exit(0)
	}

	router := mux.NewRouter()
	apiSubRoute := router.PathPrefix("/api").Subrouter()

	apiSubRoute.Path("/bookmarks").Methods(http.MethodPost).HandlerFunc(nil)
	apiSubRoute.Path("/bookmarks").Methods(http.MethodGet).HandlerFunc(nil)

}
