// generated by gocipe 89440e4dbce197f5b46d60d778de3e709012a9e0bf60a5510bf683dbf5304465; DO NOT EDIT

package rating

import (
	"github.com/gorilla/mux"
)

type responseSingle struct {
	Status   bool      `json:"status"`
	Messages []message `json:"messages"`
	Entity   *Rating   `json:"entity"`
}

type responseList struct {
	Status   bool      `json:"status"`
	Messages []message `json:"messages"`
	Entities []*Rating `json:"entities"`
}

type message struct {
	Type    rune   `json:"type"`
	Message string `json:"message"`
}

//RegisterRoutes registers routes with a mux Router
func RegisterRoutes(router *mux.Router) {

}
