// generated by gocipe 7a9000d6c7c4a975fa1ad9470a4ce01982a28eb73f76dde520a18fc9354f2521; DO NOT EDIT

package rating

import "time"

// Rating represents a summary of the feedback received for a session
type Rating struct {
	ID              *string    `json:"id"`
	RatingsCount    *int       `json:"ratings_count"`
	Score           *int       `json:"score"`
	ReactionSummary *string    `json:"reaction_summary"`
	UpdatedAt       *time.Time `json:"updated_at"`
}

// New returns an instance of Rating
func New() *Rating {
	return &Rating{
		ID:              new(string),
		RatingsCount:    new(int),
		Score:           new(int),
		ReactionSummary: new(string),
		UpdatedAt:       new(time.Time),
	}
}
