// generated by gocipe 98d04eff905d6c25e0ba7946b5abe59ef772bba989a56cb131b63b92b50cf33b; DO NOT EDIT

package rating

import (
	"github.com/gorilla/mux"
)

type responseSingle struct {
	Status   bool      `json:"status"`
	Messages []message `json:"messages"`
	Entity   *Rating   `json:"entity"`
}

type responseList struct {
	Status   bool      `json:"status"`
	Messages []message `json:"messages"`
	Entities []*Rating `json:"entities"`
}

type message struct {
	Type    rune   `json:"type"`
	Message string `json:"message"`
}

//RegisterRoutes registers routes with a mux Router
func RegisterRoutes(router *mux.Router) {

}
