// generated by gocipe a113b3c3d9f0bc69a9636981154d6293fbd50d8eed8462b35778873cde989dae; DO NOT EDIT

package rating

import (
	"database/sql"
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/mscraftsman/devcon-feedback/models"
)

var db *sql.DB

// Inject allows injection of services into the package
func Inject(database *sql.DB) {
	db = database
}

// Get returns a single Rating from database by primary key
func Get(id string) (*Rating, error) {
	var entity = New()

	if err := crudPreGet(id); err != nil {
		return nil, fmt.Errorf("error executing crudPreGet() in Get(%x) for entity 'Rating': %s", id, err)
	}

	rows, err := db.Query("SELECT t.ratings_count, t.score, t.reaction_summary, t.updated_at FROM ratings t WHERE id = $1 ORDER BY t.id ASC", id)
	if err != nil {
		return nil, err
	}

	defer rows.Close()
	for rows.Next() {

		err := rows.Scan(entity.RatingsCount, entity.Score, entity.ReactionSummary, entity.UpdatedAt)
		if err != nil {
			return nil, err
		}

	}

	if err = crudPostGet(entity); err != nil {
		return nil, fmt.Errorf("error executing crudPostGet() in Get(%x) for entity 'Rating': %s", id, err)
	}

	return entity, nil
}

// List returns a slice containing Rating records
func List(filters []models.ListFilter) ([]*Rating, error) {
	var (
		list     []*Rating
		segments []string
		values   []interface{}
		err      error
	)

	query := "SELECT t.ratings_count, t.score, t.reaction_summary, t.updated_at FROM ratings"

	if filters, err = crudPreList(filters); err != nil {
		return nil, fmt.Errorf("error executing crudPreList() in List(filters) for entity 'Rating': %s", err)
	}

	for i, filter := range filters {
		segments = append(segments, filter.Field+" "+filter.Operation+" $"+strconv.Itoa(i+1))
		values = append(values, filter.Value)
	}

	if len(segments) != 0 {
		query += " WHERE " + strings.Join(segments, " AND ")
	}

	rows, err := db.Query(query+" ORDER BY id ASC", values...)

	if err != nil {
		return nil, err
	}

	defer rows.Close()
	for rows.Next() {
		entity := New()
		err := rows.Scan(entity.RatingsCount, entity.Score, entity.ReactionSummary, entity.UpdatedAt)
		if err != nil {
			return nil, err
		}

		list = append(list, entity)

	}

	if list, err = crudPostList(list); err != nil {
		return nil, fmt.Errorf("error executing crudPostList() in List(filters) for entity 'Rating': %s", err)
	}

	return list, nil
}

// Delete deletes a Rating record from database by id primary key
func Delete(id string, tx *sql.Tx, autocommit bool) error {
	var (
		err error
	)

	if tx == nil {
		tx, err = db.Begin()
		if err != nil {
			return err
		}
	}

	stmt, err := tx.Prepare("DELETE FROM ratings WHERE id = $1")
	if err != nil {
		return err
	}

	if err := crudPreDelete(id, tx); err != nil {
		tx.Rollback()
		return fmt.Errorf("error executing crudPreDelete() in Delete(%x) for entity 'Rating': %s", id, err)
	}

	_, err = stmt.Exec(id)
	if err != nil {
		tx.Rollback()
		return fmt.Errorf("error executing transaction statement in Delete(%x) for entity 'Rating': %s", id, err)
	}

	if err := crudPostDelete(id, tx); err != nil {
		tx.Rollback()
		return fmt.Errorf("Error executing crudPostDelete() in Delete(%x) for entity 'Rating': %s", id, err)
	}

	if autocommit {
		err = tx.Commit()
		if err != nil {
			return fmt.Errorf("error committing transaction in Delete(%x) for 'Rating': %s", id, err)
		}
	}

	return err
}

// Delete deletes a Rating record from database and sets id to nil
func (entity *Rating) Delete(tx *sql.Tx, autocommit bool) error {
	var (
		err error
	)

	id := *entity.ID

	if tx == nil {
		tx, err = db.Begin()
		if err != nil {
			return err
		}
	}

	stmt, err := tx.Prepare("DELETE FROM ratings WHERE id = $1")
	if err != nil {
		return err
	}

	if err := crudPreDelete(id, tx); err != nil {
		tx.Rollback()
		return fmt.Errorf("error executing crudPreDelete() in Rating.Delete() for ID = %x : %s", id, err)
	}

	_, err = stmt.Exec(id)
	if err == nil {
		entity.ID = nil
	} else {
		tx.Rollback()
		return fmt.Errorf("error executing transaction statement in Rating.Delete() for ID = %x : %s", id, err)
	}

	if err = crudPostDelete(id, tx); err != nil {
		tx.Rollback()
		return fmt.Errorf("error executing crudPostDelete() in Rating.Delete() for ID = %x : %s", id, err)
	}

	if autocommit {
		err = tx.Commit()
		if err != nil {
			return fmt.Errorf("error committing transaction in Rating.Delete() for ID = %x : %s", id, err)
		}
	}

	return err
}

// Save either inserts or updates a Rating record based on whether or not id is nil
func (entity *Rating) Save(tx *sql.Tx, autocommit bool) error {
	if entity.ID == nil {
		return entity.Insert(tx, autocommit)
	}
	return entity.Update(tx, autocommit)
}

// Insert performs an SQL insert for Rating record and update instance with inserted id.
// Prefer using Save rather than Insert directly.
func (entity *Rating) Insert(tx *sql.Tx, autocommit bool) error {
	var (
		err error
	)

	if tx == nil {
		tx, err = db.Begin()
		if err != nil {
			return err
		}
	}
	*entity.UpdatedAt = time.Now()

	stmt, err := tx.Prepare("INSERT INTO ratings ($1, $2, $3, $4, $5) VALUES ($1, $2, $3, $4, $5)")
	if err != nil {
		return err
	}

	if err := crudPreCreate(entity, tx); err != nil {
		tx.Rollback()
		return fmt.Errorf("error executing crudPreCreate() in Rating.Insert(): %s", err)
	}

	_, err = stmt.Exec(*entity.ID, *entity.RatingsCount, *entity.Score, *entity.ReactionSummary, *entity.UpdatedAt)
	if err != nil {
		tx.Rollback()
		return fmt.Errorf("error executing transaction statement in Rating: %s", err)
	}

	if err := crudPostCreate(entity, tx); err != nil {
		tx.Rollback()
		return fmt.Errorf("error executing crudPostCreate() in Rating.Insert(): %s", err)
	}

	if autocommit {
		err = tx.Commit()
		if err != nil {
			return fmt.Errorf("error committing transaction in Rating.Insert(): %s", err)
		}
	}

	return nil
}

// Update Will execute an SQLUpdate Statement for Rating in the database. Prefer using Save instead of Update directly.
func (entity *Rating) Update(tx *sql.Tx, autocommit bool) error {
	var (
		err error
	)

	if tx == nil {
		tx, err = db.Begin()
		if err != nil {
			return err
		}
	}
	*entity.UpdatedAt = time.Now()

	stmt, err := tx.Prepare("UPDATE ratings SET ratings_count = $2, score = $3, reaction_summary = $4, updated_at = $5 WHERE id = $1")
	if err != nil {
		return err
	}

	if err := crudPreUpdate(entity, tx); err != nil {
		tx.Rollback()
		return fmt.Errorf("error executing crudPreUpdate() in Rating.Update(): %s", err)
	}

	_, err = stmt.Exec(*entity.RatingsCount, *entity.Score, *entity.ReactionSummary, *entity.UpdatedAt)
	if err != nil {
		tx.Rollback()
		return fmt.Errorf("error executing transaction statement in Rating.Update(): %s", err)
	}

	if err := crudPostUpdate(entity, tx); err != nil {
		tx.Rollback()
		return fmt.Errorf("error executing crudPostUpdate() in Rating.Update(): %s", err)
	}

	if autocommit {
		err = tx.Commit()
		if err != nil {
			return fmt.Errorf("error committing transaction in Rating.Update(): %s", err)
		}
	}

	return nil
}
