// generated by gocipe a113b3c3d9f0bc69a9636981154d6293fbd50d8eed8462b35778873cde989dae; DO NOT EDIT

package rating

import "time"

// Rating represents a summary of the feedback received for a session
type Rating struct {
	ID              *string    `json:"id"`
	RatingsCount    *int       `json:"ratings_count"`
	Score           *int       `json:"score"`
	ReactionSummary *string    `json:"reaction_summary"`
	UpdatedAt       *time.Time `json:"updated_at"`
}

// New returns an instance of Rating
func New() *Rating {
	return &Rating{
		ID:              new(string),
		RatingsCount:    new(int),
		Score:           new(int),
		ReactionSummary: new(string),
		UpdatedAt:       new(time.Time),
	}
}
