// generated by gocipe 8711bda2250e6c55fba92576b5a3047c42d034e6742f4bff5ae1f9e546907463; DO NOT EDIT

package rating

import "time"

// Rating represents a summary of the feedback received for a session
type Rating struct {
	ID              *string    `json:"id"`
	RatingsCount    *int       `json:"ratings_count"`
	Score           *int       `json:"score"`
	ReactionSummary *string    `json:"reaction_summary"`
	UpdatedAt       *time.Time `json:"updated_at"`
}

// New returns an instance of Rating
func New() *Rating {
	return &Rating{
		ID:              new(string),
		RatingsCount:    new(int),
		Score:           new(int),
		ReactionSummary: new(string),
		UpdatedAt:       new(time.Time),
	}
}
