// generated by gocipe; DO NOT EDIT

package grpcx

import (
	"context"

	log "github.com/sirupsen/logrus"
	"google.golang.org/grpc"
)

//UnaryLoggerInteceptor is a unary interceptor that handles logging for debugging and panic level errors
func UnaryLoggerInteceptor(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (interface{}, error) {
	defer func() {
		if err := recover(); err != nil {
			log.WithFields(log.Fields{"error": err, "method": info.FullMethod}).Error("GRPC Panic")
		}
	}()

	go log.WithFields(log.Fields{"method": info.FullMethod}).Debug("GRPC method invoked")
	return handler(ctx, req)
}
