-- generated by gocipe de1bb85c9a7bb2a94d27bdc90a816fda2f0c1a74eedc651da8880ddade0f7a18; DO NOT EDIT

DROP TABLE IF EXISTS visitors;

CREATE TABLE visitors (
	"id" VARCHAR(255),
	"name" VARCHAR(255) NOT NULL,
	"photo_link" VARCHAR(255),
	"status" BOOLEAN,
	
	PRIMARY KEY ("id")
);


DROP TABLE IF EXISTS feedbacks;

CREATE TABLE feedbacks (
	"id" SERIAL,
	"session_id" VARCHAR(255) NOT NULL,
	"visitor_id" VARCHAR(255) NOT NULL,
	"reaction_1" VARCHAR(2) NOT NULL,
	"reaction_2" VARCHAR(2),
	"reaction_3" VARCHAR(3),
	"reaction_4" TEXT,
	"created_at" TIMESTAMP NOT NULL,
	UNIQUE(session_id, visitor_id),
	PRIMARY KEY ("id")
);


DROP TABLE IF EXISTS ratings;

CREATE TABLE ratings (
	"id" VARCHAR(255),
	"ratings_count" INT NOT NULL,
	"score" INT NOT NULL,
	"reaction_summary" JSONB NOT NULL,
	"updated_at" TIMESTAMP NOT NULL,
	
	PRIMARY KEY ("id")
);


