-- generated by gocipe 8711bda2250e6c55fba92576b5a3047c42d034e6742f4bff5ae1f9e546907463; DO NOT EDIT

DROP TABLE IF EXISTS sessions;

CREATE TABLE sessions (
	"id" VARCHAR(255),
	"title" VARCHAR(255) NOT NULL,
	"description" Text,
	"level" CHAR(1),
	"language" CHAR(2),
	"format" CHAR(1),
	"room" VARCHAR(255),
	"speakers" TEXT,
	"start_at" TIMESTAMP NOT NULL,
	"end_at" TIMESTAMP NOT NULL,
	"status" BOOLEAN NOT NULL,
	PRIMARY KEY ("id")
);


DROP TABLE IF EXISTS visitors;

CREATE TABLE visitors (
	"id" VARCHAR(255),
	"name" VARCHAR(255) NOT NULL,
	"photo_link" VARCHAR(255),
	PRIMARY KEY ("id")
);


DROP TABLE IF EXISTS feedbacks;

CREATE TABLE feedbacks (
	"id" SERIAL,
	"visitor_id" INT NOT NULL,
	"reaction_1" CHAR(1) NOT NULL,
	"reaction_2" CHAR(1),
	"reaction_3" CHAR(1),
	"reaction_4" TEXT,
	"created_at" TIMESTAMP NOT NULL,
	PRIMARY KEY ("id")
);


DROP TABLE IF EXISTS ratings;

CREATE TABLE ratings (
	"id" VARCHAR(255),
	"ratings_count" INT NOT NULL,
	"score" INT NOT NULL,
	"reaction_summary" JSONB NOT NULL,
	"updated_at" TIMESTAMP NOT NULL,
	PRIMARY KEY ("id")
);


