// generated by gocipe; DO NOT EDIT

package admin

const (

	// PermCreateFeedback is a permission token to PermCreateFeedback
	PermCreateFeedback = "A"

	// PermEditFeedback is a permission token to PermEditFeedback
	PermEditFeedback = "B"

	// PermEditFeedbackAny is a permission token to PermEditFeedbackAny
	PermEditFeedbackAny = "C"

	// PermViewFeedback is a permission token to PermViewFeedback
	PermViewFeedback = "D"

	// PermViewFeedbackAny is a permission token to PermViewFeedbackAny
	PermViewFeedbackAny = "E"

	// PermListFeedback is a permission token to PermListFeedback
	PermListFeedback = "F"

	// PermListFeedbackAny is a permission token to PermListFeedbackAny
	PermListFeedbackAny = "G"

	// PermDeleteFeedback is a permission token to PermDeleteFeedback
	PermDeleteFeedback = "H"

	// PermDeleteFeedbackAny is a permission token to PermDeleteFeedbackAny
	PermDeleteFeedbackAny = "I"

	// PermLookupFeedback is a permission token to PermLookupFeedback
	PermLookupFeedback = "J"

	// PermLookupFeedbackAny is a permission token to PermLookupFeedbackAny
	PermLookupFeedbackAny = "K"

	// PermCreateVisitor is a permission token to PermCreateVisitor
	PermCreateVisitor = "L"

	// PermEditVisitor is a permission token to PermEditVisitor
	PermEditVisitor = "M"

	// PermEditVisitorAny is a permission token to PermEditVisitorAny
	PermEditVisitorAny = "N"

	// PermViewVisitor is a permission token to PermViewVisitor
	PermViewVisitor = "O"

	// PermViewVisitorAny is a permission token to PermViewVisitorAny
	PermViewVisitorAny = "P"

	// PermListVisitor is a permission token to PermListVisitor
	PermListVisitor = "Q"

	// PermListVisitorAny is a permission token to PermListVisitorAny
	PermListVisitorAny = "R"

	// PermDeleteVisitor is a permission token to PermDeleteVisitor
	PermDeleteVisitor = "S"

	// PermDeleteVisitorAny is a permission token to PermDeleteVisitorAny
	PermDeleteVisitorAny = "T"

	// PermLookupVisitor is a permission token to PermLookupVisitor
	PermLookupVisitor = "U"

	// PermLookupVisitorAny is a permission token to PermLookupVisitorAny
	PermLookupVisitorAny = "V"

	// PermCreateRating is a permission token to PermCreateRating
	PermCreateRating = "W"

	// PermEditRating is a permission token to PermEditRating
	PermEditRating = "X"

	// PermEditRatingAny is a permission token to PermEditRatingAny
	PermEditRatingAny = "Y"

	// PermViewRating is a permission token to PermViewRating
	PermViewRating = "Z"

	// PermViewRatingAny is a permission token to PermViewRatingAny
	PermViewRatingAny = "["

	// PermListRating is a permission token to PermListRating
	PermListRating = "]"

	// PermListRatingAny is a permission token to PermListRatingAny
	PermListRatingAny = "_"

	// PermDeleteRating is a permission token to PermDeleteRating
	PermDeleteRating = "a"

	// PermDeleteRatingAny is a permission token to PermDeleteRatingAny
	PermDeleteRatingAny = "b"

	// PermLookupRating is a permission token to PermLookupRating
	PermLookupRating = "c"

	// PermLookupRatingAny is a permission token to PermLookupRatingAny
	PermLookupRatingAny = "d"
)
