// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service_admin.proto

package admin

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	models "github.com/mscraftsman/devcon-feedback/models"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Filter represents a filter that can be applied for listing requests
type Filter struct {
	Field                string   `protobuf:"bytes,1,opt,name=Field,proto3" json:"Field,omitempty"`
	Operation            string   `protobuf:"bytes,2,opt,name=Operation,proto3" json:"Operation,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_4307915f2bfdd4f6, []int{0}
}

func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (m *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(m, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *Filter) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *Filter) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// GetRequest represents a request to allow getting a single entity
type GetRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	ID                   string   `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4307915f2bfdd4f6, []int{1}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

// ListRequest represents a request to allow listing of entities
type ListRequest struct {
	Key                  string           `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	ListOpts             *models.ListOpts `protobuf:"bytes,2,opt,name=ListOpts,proto3" json:"ListOpts,omitempty"`
	Filters              []*Filter        `protobuf:"bytes,3,rep,name=Filters,proto3" json:"Filters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4307915f2bfdd4f6, []int{2}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ListRequest) GetListOpts() *models.ListOpts {
	if m != nil {
		return m.ListOpts
	}
	return nil
}

func (m *ListRequest) GetFilters() []*Filter {
	if m != nil {
		return m.Filters
	}
	return nil
}

// CountResponse represents a response to a Count<Entity> Request
type CountResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountResponse) Reset()         { *m = CountResponse{} }
func (m *CountResponse) String() string { return proto.CompactTextString(m) }
func (*CountResponse) ProtoMessage()    {}
func (*CountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4307915f2bfdd4f6, []int{3}
}

func (m *CountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountResponse.Unmarshal(m, b)
}
func (m *CountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountResponse.Marshal(b, m, deterministic)
}
func (m *CountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountResponse.Merge(m, src)
}
func (m *CountResponse) XXX_Size() int {
	return xxx_messageInfo_CountResponse.Size(m)
}
func (m *CountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CountResponse proto.InternalMessageInfo

func (m *CountResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

// DeleteRequest represents a request to allow deleting an entity
type DeleteRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	ID                   string   `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4307915f2bfdd4f6, []int{4}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DeleteRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

// DeleteResponse represents result to a DeleteRequest
type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4307915f2bfdd4f6, []int{5}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

// UploadOpts represents message to define upload options of files
type UploadOpts struct {
	Watermark            bool     `protobuf:"varint,1,opt,name=Watermark,proto3" json:"Watermark,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadOpts) Reset()         { *m = UploadOpts{} }
func (m *UploadOpts) String() string { return proto.CompactTextString(m) }
func (*UploadOpts) ProtoMessage()    {}
func (*UploadOpts) Descriptor() ([]byte, []int) {
	return fileDescriptor_4307915f2bfdd4f6, []int{6}
}

func (m *UploadOpts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadOpts.Unmarshal(m, b)
}
func (m *UploadOpts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadOpts.Marshal(b, m, deterministic)
}
func (m *UploadOpts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadOpts.Merge(m, src)
}
func (m *UploadOpts) XXX_Size() int {
	return xxx_messageInfo_UploadOpts.Size(m)
}
func (m *UploadOpts) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadOpts.DiscardUnknown(m)
}

var xxx_messageInfo_UploadOpts proto.InternalMessageInfo

func (m *UploadOpts) GetWatermark() bool {
	if m != nil {
		return m.Watermark
	}
	return false
}

// UploadRequest represents message to allow uploading of files
type UploadRequest struct {
	Key                  string      `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	ID                   string      `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	Field                string      `protobuf:"bytes,3,opt,name=Field,proto3" json:"Field,omitempty"`
	Filename             string      `protobuf:"bytes,4,opt,name=Filename,proto3" json:"Filename,omitempty"`
	Content              []byte      `protobuf:"bytes,5,opt,name=Content,proto3" json:"Content,omitempty"`
	UploadOptions        *UploadOpts `protobuf:"bytes,6,opt,name=UploadOptions,proto3" json:"UploadOptions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UploadRequest) Reset()         { *m = UploadRequest{} }
func (m *UploadRequest) String() string { return proto.CompactTextString(m) }
func (*UploadRequest) ProtoMessage()    {}
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4307915f2bfdd4f6, []int{7}
}

func (m *UploadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadRequest.Unmarshal(m, b)
}
func (m *UploadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadRequest.Marshal(b, m, deterministic)
}
func (m *UploadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadRequest.Merge(m, src)
}
func (m *UploadRequest) XXX_Size() int {
	return xxx_messageInfo_UploadRequest.Size(m)
}
func (m *UploadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadRequest proto.InternalMessageInfo

func (m *UploadRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *UploadRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UploadRequest) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *UploadRequest) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *UploadRequest) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *UploadRequest) GetUploadOptions() *UploadOpts {
	if m != nil {
		return m.UploadOptions
	}
	return nil
}

// UploadResponse represents result to an UploadRequest
type UploadResponse struct {
	URI                  string   `protobuf:"bytes,1,opt,name=URI,proto3" json:"URI,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadResponse) Reset()         { *m = UploadResponse{} }
func (m *UploadResponse) String() string { return proto.CompactTextString(m) }
func (*UploadResponse) ProtoMessage()    {}
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4307915f2bfdd4f6, []int{8}
}

func (m *UploadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadResponse.Unmarshal(m, b)
}
func (m *UploadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadResponse.Marshal(b, m, deterministic)
}
func (m *UploadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadResponse.Merge(m, src)
}
func (m *UploadResponse) XXX_Size() int {
	return xxx_messageInfo_UploadResponse.Size(m)
}
func (m *UploadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadResponse proto.InternalMessageInfo

func (m *UploadResponse) GetURI() string {
	if m != nil {
		return m.URI
	}
	return ""
}

// LookupRequest represents a request to lookup an entity by its label
type LookupRequest struct {
	Key                  string           `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Term                 string           `protobuf:"bytes,2,opt,name=Term,proto3" json:"Term,omitempty"`
	ListOpts             *models.ListOpts `protobuf:"bytes,3,opt,name=ListOpts,proto3" json:"ListOpts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *LookupRequest) Reset()         { *m = LookupRequest{} }
func (m *LookupRequest) String() string { return proto.CompactTextString(m) }
func (*LookupRequest) ProtoMessage()    {}
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4307915f2bfdd4f6, []int{9}
}

func (m *LookupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookupRequest.Unmarshal(m, b)
}
func (m *LookupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookupRequest.Marshal(b, m, deterministic)
}
func (m *LookupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookupRequest.Merge(m, src)
}
func (m *LookupRequest) XXX_Size() int {
	return xxx_messageInfo_LookupRequest.Size(m)
}
func (m *LookupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LookupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LookupRequest proto.InternalMessageInfo

func (m *LookupRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *LookupRequest) GetTerm() string {
	if m != nil {
		return m.Term
	}
	return ""
}

func (m *LookupRequest) GetListOpts() *models.ListOpts {
	if m != nil {
		return m.ListOpts
	}
	return nil
}

// LookupResult represents one (of many) results for an entity lookup request
type LookupResult struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Label                string   `protobuf:"bytes,2,opt,name=Label,proto3" json:"Label,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LookupResult) Reset()         { *m = LookupResult{} }
func (m *LookupResult) String() string { return proto.CompactTextString(m) }
func (*LookupResult) ProtoMessage()    {}
func (*LookupResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_4307915f2bfdd4f6, []int{10}
}

func (m *LookupResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookupResult.Unmarshal(m, b)
}
func (m *LookupResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookupResult.Marshal(b, m, deterministic)
}
func (m *LookupResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookupResult.Merge(m, src)
}
func (m *LookupResult) XXX_Size() int {
	return xxx_messageInfo_LookupResult.Size(m)
}
func (m *LookupResult) XXX_DiscardUnknown() {
	xxx_messageInfo_LookupResult.DiscardUnknown(m)
}

var xxx_messageInfo_LookupResult proto.InternalMessageInfo

func (m *LookupResult) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *LookupResult) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *LookupResult) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

// LookupResponse represents a series of results to a lookup request
type LookupResponse struct {
	Result               []*LookupResult `protobuf:"bytes,1,rep,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *LookupResponse) Reset()         { *m = LookupResponse{} }
func (m *LookupResponse) String() string { return proto.CompactTextString(m) }
func (*LookupResponse) ProtoMessage()    {}
func (*LookupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4307915f2bfdd4f6, []int{11}
}

func (m *LookupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookupResponse.Unmarshal(m, b)
}
func (m *LookupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookupResponse.Marshal(b, m, deterministic)
}
func (m *LookupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookupResponse.Merge(m, src)
}
func (m *LookupResponse) XXX_Size() int {
	return xxx_messageInfo_LookupResponse.Size(m)
}
func (m *LookupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LookupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LookupResponse proto.InternalMessageInfo

func (m *LookupResponse) GetResult() []*LookupResult {
	if m != nil {
		return m.Result
	}
	return nil
}

// CreateFeedbackRequest represents a request to allow creation of entity of type Feedback
type CreateFeedbackRequest struct {
	Key                  string           `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Feedback             *models.Feedback `protobuf:"bytes,2,opt,name=Feedback,proto3" json:"Feedback,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateFeedbackRequest) Reset()         { *m = CreateFeedbackRequest{} }
func (m *CreateFeedbackRequest) String() string { return proto.CompactTextString(m) }
func (*CreateFeedbackRequest) ProtoMessage()    {}
func (*CreateFeedbackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4307915f2bfdd4f6, []int{12}
}

func (m *CreateFeedbackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFeedbackRequest.Unmarshal(m, b)
}
func (m *CreateFeedbackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFeedbackRequest.Marshal(b, m, deterministic)
}
func (m *CreateFeedbackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFeedbackRequest.Merge(m, src)
}
func (m *CreateFeedbackRequest) XXX_Size() int {
	return xxx_messageInfo_CreateFeedbackRequest.Size(m)
}
func (m *CreateFeedbackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFeedbackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFeedbackRequest proto.InternalMessageInfo

func (m *CreateFeedbackRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *CreateFeedbackRequest) GetFeedback() *models.Feedback {
	if m != nil {
		return m.Feedback
	}
	return nil
}

// CreateFeedbackResponse represents result to a CreateFeedbackRequest
type CreateFeedbackResponse struct {
	Feedback             *models.Feedback `protobuf:"bytes,1,opt,name=Feedback,proto3" json:"Feedback,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateFeedbackResponse) Reset()         { *m = CreateFeedbackResponse{} }
func (m *CreateFeedbackResponse) String() string { return proto.CompactTextString(m) }
func (*CreateFeedbackResponse) ProtoMessage()    {}
func (*CreateFeedbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4307915f2bfdd4f6, []int{13}
}

func (m *CreateFeedbackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFeedbackResponse.Unmarshal(m, b)
}
func (m *CreateFeedbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFeedbackResponse.Marshal(b, m, deterministic)
}
func (m *CreateFeedbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFeedbackResponse.Merge(m, src)
}
func (m *CreateFeedbackResponse) XXX_Size() int {
	return xxx_messageInfo_CreateFeedbackResponse.Size(m)
}
func (m *CreateFeedbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFeedbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFeedbackResponse proto.InternalMessageInfo

func (m *CreateFeedbackResponse) GetFeedback() *models.Feedback {
	if m != nil {
		return m.Feedback
	}
	return nil
}

// GetFeedbackResponse represents result to a GetRequest
type GetFeedbackResponse struct {
	Feedback             *models.Feedback `protobuf:"bytes,1,opt,name=Feedback,proto3" json:"Feedback,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetFeedbackResponse) Reset()         { *m = GetFeedbackResponse{} }
func (m *GetFeedbackResponse) String() string { return proto.CompactTextString(m) }
func (*GetFeedbackResponse) ProtoMessage()    {}
func (*GetFeedbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4307915f2bfdd4f6, []int{14}
}

func (m *GetFeedbackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFeedbackResponse.Unmarshal(m, b)
}
func (m *GetFeedbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFeedbackResponse.Marshal(b, m, deterministic)
}
func (m *GetFeedbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeedbackResponse.Merge(m, src)
}
func (m *GetFeedbackResponse) XXX_Size() int {
	return xxx_messageInfo_GetFeedbackResponse.Size(m)
}
func (m *GetFeedbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeedbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeedbackResponse proto.InternalMessageInfo

func (m *GetFeedbackResponse) GetFeedback() *models.Feedback {
	if m != nil {
		return m.Feedback
	}
	return nil
}

// ListFeedbacksResponse represents result to a ListRequest
type ListFeedbacksResponse struct {
	Feedbacks            []*models.Feedback `protobuf:"bytes,1,rep,name=Feedbacks,proto3" json:"Feedbacks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ListFeedbacksResponse) Reset()         { *m = ListFeedbacksResponse{} }
func (m *ListFeedbacksResponse) String() string { return proto.CompactTextString(m) }
func (*ListFeedbacksResponse) ProtoMessage()    {}
func (*ListFeedbacksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4307915f2bfdd4f6, []int{15}
}

func (m *ListFeedbacksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFeedbacksResponse.Unmarshal(m, b)
}
func (m *ListFeedbacksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFeedbacksResponse.Marshal(b, m, deterministic)
}
func (m *ListFeedbacksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFeedbacksResponse.Merge(m, src)
}
func (m *ListFeedbacksResponse) XXX_Size() int {
	return xxx_messageInfo_ListFeedbacksResponse.Size(m)
}
func (m *ListFeedbacksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFeedbacksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListFeedbacksResponse proto.InternalMessageInfo

func (m *ListFeedbacksResponse) GetFeedbacks() []*models.Feedback {
	if m != nil {
		return m.Feedbacks
	}
	return nil
}

// UpdateFeedbackRequest represents a request to allow updating one entity of type Feedback
type UpdateFeedbackRequest struct {
	Key                  string           `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Feedback             *models.Feedback `protobuf:"bytes,2,opt,name=Feedback,proto3" json:"Feedback,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UpdateFeedbackRequest) Reset()         { *m = UpdateFeedbackRequest{} }
func (m *UpdateFeedbackRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateFeedbackRequest) ProtoMessage()    {}
func (*UpdateFeedbackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4307915f2bfdd4f6, []int{16}
}

func (m *UpdateFeedbackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFeedbackRequest.Unmarshal(m, b)
}
func (m *UpdateFeedbackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFeedbackRequest.Marshal(b, m, deterministic)
}
func (m *UpdateFeedbackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFeedbackRequest.Merge(m, src)
}
func (m *UpdateFeedbackRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateFeedbackRequest.Size(m)
}
func (m *UpdateFeedbackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFeedbackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFeedbackRequest proto.InternalMessageInfo

func (m *UpdateFeedbackRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *UpdateFeedbackRequest) GetFeedback() *models.Feedback {
	if m != nil {
		return m.Feedback
	}
	return nil
}

// UpdateFeedbackResponse represents result to an UpdateFeedbackRequest
type UpdateFeedbackResponse struct {
	Feedback             *models.Feedback `protobuf:"bytes,1,opt,name=Feedback,proto3" json:"Feedback,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UpdateFeedbackResponse) Reset()         { *m = UpdateFeedbackResponse{} }
func (m *UpdateFeedbackResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateFeedbackResponse) ProtoMessage()    {}
func (*UpdateFeedbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4307915f2bfdd4f6, []int{17}
}

func (m *UpdateFeedbackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFeedbackResponse.Unmarshal(m, b)
}
func (m *UpdateFeedbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFeedbackResponse.Marshal(b, m, deterministic)
}
func (m *UpdateFeedbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFeedbackResponse.Merge(m, src)
}
func (m *UpdateFeedbackResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateFeedbackResponse.Size(m)
}
func (m *UpdateFeedbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFeedbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFeedbackResponse proto.InternalMessageInfo

func (m *UpdateFeedbackResponse) GetFeedback() *models.Feedback {
	if m != nil {
		return m.Feedback
	}
	return nil
}

// CreateVisitorRequest represents a request to allow creation of entity of type Visitor
type CreateVisitorRequest struct {
	Key                  string          `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Visitor              *models.Visitor `protobuf:"bytes,2,opt,name=Visitor,proto3" json:"Visitor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateVisitorRequest) Reset()         { *m = CreateVisitorRequest{} }
func (m *CreateVisitorRequest) String() string { return proto.CompactTextString(m) }
func (*CreateVisitorRequest) ProtoMessage()    {}
func (*CreateVisitorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4307915f2bfdd4f6, []int{18}
}

func (m *CreateVisitorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVisitorRequest.Unmarshal(m, b)
}
func (m *CreateVisitorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVisitorRequest.Marshal(b, m, deterministic)
}
func (m *CreateVisitorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVisitorRequest.Merge(m, src)
}
func (m *CreateVisitorRequest) XXX_Size() int {
	return xxx_messageInfo_CreateVisitorRequest.Size(m)
}
func (m *CreateVisitorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVisitorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVisitorRequest proto.InternalMessageInfo

func (m *CreateVisitorRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *CreateVisitorRequest) GetVisitor() *models.Visitor {
	if m != nil {
		return m.Visitor
	}
	return nil
}

// CreateVisitorResponse represents result to a CreateVisitorRequest
type CreateVisitorResponse struct {
	Visitor              *models.Visitor `protobuf:"bytes,1,opt,name=Visitor,proto3" json:"Visitor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateVisitorResponse) Reset()         { *m = CreateVisitorResponse{} }
func (m *CreateVisitorResponse) String() string { return proto.CompactTextString(m) }
func (*CreateVisitorResponse) ProtoMessage()    {}
func (*CreateVisitorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4307915f2bfdd4f6, []int{19}
}

func (m *CreateVisitorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVisitorResponse.Unmarshal(m, b)
}
func (m *CreateVisitorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVisitorResponse.Marshal(b, m, deterministic)
}
func (m *CreateVisitorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVisitorResponse.Merge(m, src)
}
func (m *CreateVisitorResponse) XXX_Size() int {
	return xxx_messageInfo_CreateVisitorResponse.Size(m)
}
func (m *CreateVisitorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVisitorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVisitorResponse proto.InternalMessageInfo

func (m *CreateVisitorResponse) GetVisitor() *models.Visitor {
	if m != nil {
		return m.Visitor
	}
	return nil
}

// GetVisitorResponse represents result to a GetRequest
type GetVisitorResponse struct {
	Visitor              *models.Visitor `protobuf:"bytes,1,opt,name=Visitor,proto3" json:"Visitor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetVisitorResponse) Reset()         { *m = GetVisitorResponse{} }
func (m *GetVisitorResponse) String() string { return proto.CompactTextString(m) }
func (*GetVisitorResponse) ProtoMessage()    {}
func (*GetVisitorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4307915f2bfdd4f6, []int{20}
}

func (m *GetVisitorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVisitorResponse.Unmarshal(m, b)
}
func (m *GetVisitorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVisitorResponse.Marshal(b, m, deterministic)
}
func (m *GetVisitorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVisitorResponse.Merge(m, src)
}
func (m *GetVisitorResponse) XXX_Size() int {
	return xxx_messageInfo_GetVisitorResponse.Size(m)
}
func (m *GetVisitorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVisitorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVisitorResponse proto.InternalMessageInfo

func (m *GetVisitorResponse) GetVisitor() *models.Visitor {
	if m != nil {
		return m.Visitor
	}
	return nil
}

// ListVisitorsResponse represents result to a ListRequest
type ListVisitorsResponse struct {
	Visitors             []*models.Visitor `protobuf:"bytes,1,rep,name=Visitors,proto3" json:"Visitors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListVisitorsResponse) Reset()         { *m = ListVisitorsResponse{} }
func (m *ListVisitorsResponse) String() string { return proto.CompactTextString(m) }
func (*ListVisitorsResponse) ProtoMessage()    {}
func (*ListVisitorsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4307915f2bfdd4f6, []int{21}
}

func (m *ListVisitorsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListVisitorsResponse.Unmarshal(m, b)
}
func (m *ListVisitorsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListVisitorsResponse.Marshal(b, m, deterministic)
}
func (m *ListVisitorsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListVisitorsResponse.Merge(m, src)
}
func (m *ListVisitorsResponse) XXX_Size() int {
	return xxx_messageInfo_ListVisitorsResponse.Size(m)
}
func (m *ListVisitorsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListVisitorsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListVisitorsResponse proto.InternalMessageInfo

func (m *ListVisitorsResponse) GetVisitors() []*models.Visitor {
	if m != nil {
		return m.Visitors
	}
	return nil
}

// UpdateVisitorRequest represents a request to allow updating one entity of type Visitor
type UpdateVisitorRequest struct {
	Key                  string          `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Visitor              *models.Visitor `protobuf:"bytes,2,opt,name=Visitor,proto3" json:"Visitor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateVisitorRequest) Reset()         { *m = UpdateVisitorRequest{} }
func (m *UpdateVisitorRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateVisitorRequest) ProtoMessage()    {}
func (*UpdateVisitorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4307915f2bfdd4f6, []int{22}
}

func (m *UpdateVisitorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateVisitorRequest.Unmarshal(m, b)
}
func (m *UpdateVisitorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateVisitorRequest.Marshal(b, m, deterministic)
}
func (m *UpdateVisitorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateVisitorRequest.Merge(m, src)
}
func (m *UpdateVisitorRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateVisitorRequest.Size(m)
}
func (m *UpdateVisitorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateVisitorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateVisitorRequest proto.InternalMessageInfo

func (m *UpdateVisitorRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *UpdateVisitorRequest) GetVisitor() *models.Visitor {
	if m != nil {
		return m.Visitor
	}
	return nil
}

// UpdateVisitorResponse represents result to an UpdateVisitorRequest
type UpdateVisitorResponse struct {
	Visitor              *models.Visitor `protobuf:"bytes,1,opt,name=Visitor,proto3" json:"Visitor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateVisitorResponse) Reset()         { *m = UpdateVisitorResponse{} }
func (m *UpdateVisitorResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateVisitorResponse) ProtoMessage()    {}
func (*UpdateVisitorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4307915f2bfdd4f6, []int{23}
}

func (m *UpdateVisitorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateVisitorResponse.Unmarshal(m, b)
}
func (m *UpdateVisitorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateVisitorResponse.Marshal(b, m, deterministic)
}
func (m *UpdateVisitorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateVisitorResponse.Merge(m, src)
}
func (m *UpdateVisitorResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateVisitorResponse.Size(m)
}
func (m *UpdateVisitorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateVisitorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateVisitorResponse proto.InternalMessageInfo

func (m *UpdateVisitorResponse) GetVisitor() *models.Visitor {
	if m != nil {
		return m.Visitor
	}
	return nil
}

// CreateRatingRequest represents a request to allow creation of entity of type Rating
type CreateRatingRequest struct {
	Key                  string         `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Rating               *models.Rating `protobuf:"bytes,2,opt,name=Rating,proto3" json:"Rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateRatingRequest) Reset()         { *m = CreateRatingRequest{} }
func (m *CreateRatingRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRatingRequest) ProtoMessage()    {}
func (*CreateRatingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4307915f2bfdd4f6, []int{24}
}

func (m *CreateRatingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRatingRequest.Unmarshal(m, b)
}
func (m *CreateRatingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRatingRequest.Marshal(b, m, deterministic)
}
func (m *CreateRatingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRatingRequest.Merge(m, src)
}
func (m *CreateRatingRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRatingRequest.Size(m)
}
func (m *CreateRatingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRatingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRatingRequest proto.InternalMessageInfo

func (m *CreateRatingRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *CreateRatingRequest) GetRating() *models.Rating {
	if m != nil {
		return m.Rating
	}
	return nil
}

// CreateRatingResponse represents result to a CreateRatingRequest
type CreateRatingResponse struct {
	Rating               *models.Rating `protobuf:"bytes,1,opt,name=Rating,proto3" json:"Rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateRatingResponse) Reset()         { *m = CreateRatingResponse{} }
func (m *CreateRatingResponse) String() string { return proto.CompactTextString(m) }
func (*CreateRatingResponse) ProtoMessage()    {}
func (*CreateRatingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4307915f2bfdd4f6, []int{25}
}

func (m *CreateRatingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRatingResponse.Unmarshal(m, b)
}
func (m *CreateRatingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRatingResponse.Marshal(b, m, deterministic)
}
func (m *CreateRatingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRatingResponse.Merge(m, src)
}
func (m *CreateRatingResponse) XXX_Size() int {
	return xxx_messageInfo_CreateRatingResponse.Size(m)
}
func (m *CreateRatingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRatingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRatingResponse proto.InternalMessageInfo

func (m *CreateRatingResponse) GetRating() *models.Rating {
	if m != nil {
		return m.Rating
	}
	return nil
}

// GetRatingResponse represents result to a GetRequest
type GetRatingResponse struct {
	Rating               *models.Rating `protobuf:"bytes,1,opt,name=Rating,proto3" json:"Rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetRatingResponse) Reset()         { *m = GetRatingResponse{} }
func (m *GetRatingResponse) String() string { return proto.CompactTextString(m) }
func (*GetRatingResponse) ProtoMessage()    {}
func (*GetRatingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4307915f2bfdd4f6, []int{26}
}

func (m *GetRatingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRatingResponse.Unmarshal(m, b)
}
func (m *GetRatingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRatingResponse.Marshal(b, m, deterministic)
}
func (m *GetRatingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRatingResponse.Merge(m, src)
}
func (m *GetRatingResponse) XXX_Size() int {
	return xxx_messageInfo_GetRatingResponse.Size(m)
}
func (m *GetRatingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRatingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRatingResponse proto.InternalMessageInfo

func (m *GetRatingResponse) GetRating() *models.Rating {
	if m != nil {
		return m.Rating
	}
	return nil
}

// ListRatingsResponse represents result to a ListRequest
type ListRatingsResponse struct {
	Ratings              []*models.Rating `protobuf:"bytes,1,rep,name=Ratings,proto3" json:"Ratings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListRatingsResponse) Reset()         { *m = ListRatingsResponse{} }
func (m *ListRatingsResponse) String() string { return proto.CompactTextString(m) }
func (*ListRatingsResponse) ProtoMessage()    {}
func (*ListRatingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4307915f2bfdd4f6, []int{27}
}

func (m *ListRatingsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRatingsResponse.Unmarshal(m, b)
}
func (m *ListRatingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRatingsResponse.Marshal(b, m, deterministic)
}
func (m *ListRatingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRatingsResponse.Merge(m, src)
}
func (m *ListRatingsResponse) XXX_Size() int {
	return xxx_messageInfo_ListRatingsResponse.Size(m)
}
func (m *ListRatingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRatingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRatingsResponse proto.InternalMessageInfo

func (m *ListRatingsResponse) GetRatings() []*models.Rating {
	if m != nil {
		return m.Ratings
	}
	return nil
}

// UpdateRatingRequest represents a request to allow updating one entity of type Rating
type UpdateRatingRequest struct {
	Key                  string         `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Rating               *models.Rating `protobuf:"bytes,2,opt,name=Rating,proto3" json:"Rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpdateRatingRequest) Reset()         { *m = UpdateRatingRequest{} }
func (m *UpdateRatingRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRatingRequest) ProtoMessage()    {}
func (*UpdateRatingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4307915f2bfdd4f6, []int{28}
}

func (m *UpdateRatingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRatingRequest.Unmarshal(m, b)
}
func (m *UpdateRatingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRatingRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRatingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRatingRequest.Merge(m, src)
}
func (m *UpdateRatingRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRatingRequest.Size(m)
}
func (m *UpdateRatingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRatingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRatingRequest proto.InternalMessageInfo

func (m *UpdateRatingRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *UpdateRatingRequest) GetRating() *models.Rating {
	if m != nil {
		return m.Rating
	}
	return nil
}

// UpdateRatingResponse represents result to an UpdateRatingRequest
type UpdateRatingResponse struct {
	Rating               *models.Rating `protobuf:"bytes,1,opt,name=Rating,proto3" json:"Rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpdateRatingResponse) Reset()         { *m = UpdateRatingResponse{} }
func (m *UpdateRatingResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateRatingResponse) ProtoMessage()    {}
func (*UpdateRatingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4307915f2bfdd4f6, []int{29}
}

func (m *UpdateRatingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRatingResponse.Unmarshal(m, b)
}
func (m *UpdateRatingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRatingResponse.Marshal(b, m, deterministic)
}
func (m *UpdateRatingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRatingResponse.Merge(m, src)
}
func (m *UpdateRatingResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateRatingResponse.Size(m)
}
func (m *UpdateRatingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRatingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRatingResponse proto.InternalMessageInfo

func (m *UpdateRatingResponse) GetRating() *models.Rating {
	if m != nil {
		return m.Rating
	}
	return nil
}

func init() {
	proto.RegisterType((*Filter)(nil), "admin.Filter")
	proto.RegisterType((*GetRequest)(nil), "admin.GetRequest")
	proto.RegisterType((*ListRequest)(nil), "admin.ListRequest")
	proto.RegisterType((*CountResponse)(nil), "admin.CountResponse")
	proto.RegisterType((*DeleteRequest)(nil), "admin.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "admin.DeleteResponse")
	proto.RegisterType((*UploadOpts)(nil), "admin.UploadOpts")
	proto.RegisterType((*UploadRequest)(nil), "admin.UploadRequest")
	proto.RegisterType((*UploadResponse)(nil), "admin.UploadResponse")
	proto.RegisterType((*LookupRequest)(nil), "admin.LookupRequest")
	proto.RegisterType((*LookupResult)(nil), "admin.LookupResult")
	proto.RegisterType((*LookupResponse)(nil), "admin.LookupResponse")
	proto.RegisterType((*CreateFeedbackRequest)(nil), "admin.CreateFeedbackRequest")
	proto.RegisterType((*CreateFeedbackResponse)(nil), "admin.CreateFeedbackResponse")
	proto.RegisterType((*GetFeedbackResponse)(nil), "admin.GetFeedbackResponse")
	proto.RegisterType((*ListFeedbacksResponse)(nil), "admin.ListFeedbacksResponse")
	proto.RegisterType((*UpdateFeedbackRequest)(nil), "admin.UpdateFeedbackRequest")
	proto.RegisterType((*UpdateFeedbackResponse)(nil), "admin.UpdateFeedbackResponse")
	proto.RegisterType((*CreateVisitorRequest)(nil), "admin.CreateVisitorRequest")
	proto.RegisterType((*CreateVisitorResponse)(nil), "admin.CreateVisitorResponse")
	proto.RegisterType((*GetVisitorResponse)(nil), "admin.GetVisitorResponse")
	proto.RegisterType((*ListVisitorsResponse)(nil), "admin.ListVisitorsResponse")
	proto.RegisterType((*UpdateVisitorRequest)(nil), "admin.UpdateVisitorRequest")
	proto.RegisterType((*UpdateVisitorResponse)(nil), "admin.UpdateVisitorResponse")
	proto.RegisterType((*CreateRatingRequest)(nil), "admin.CreateRatingRequest")
	proto.RegisterType((*CreateRatingResponse)(nil), "admin.CreateRatingResponse")
	proto.RegisterType((*GetRatingResponse)(nil), "admin.GetRatingResponse")
	proto.RegisterType((*ListRatingsResponse)(nil), "admin.ListRatingsResponse")
	proto.RegisterType((*UpdateRatingRequest)(nil), "admin.UpdateRatingRequest")
	proto.RegisterType((*UpdateRatingResponse)(nil), "admin.UpdateRatingResponse")
}

func init() { proto.RegisterFile("service_admin.proto", fileDescriptor_4307915f2bfdd4f6) }

var fileDescriptor_4307915f2bfdd4f6 = []byte{
	// 995 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0x6d, 0x6f, 0xdb, 0x36,
	0x10, 0x86, 0xe2, 0xc6, 0x89, 0x2f, 0xb6, 0x9b, 0xd2, 0x4e, 0xa1, 0x29, 0x1e, 0x10, 0x08, 0xd8,
	0x96, 0xbd, 0x39, 0x58, 0x86, 0xa1, 0xdd, 0xda, 0x34, 0x68, 0x1d, 0xd8, 0x48, 0x97, 0x22, 0x80,
	0xba, 0xb4, 0xc0, 0xbe, 0x0c, 0xb2, 0xc5, 0x76, 0x42, 0x64, 0xc9, 0x13, 0xe9, 0x00, 0xfb, 0x63,
	0xfb, 0x59, 0xfb, 0x0d, 0x83, 0xc8, 0x23, 0xf5, 0x62, 0xda, 0xa9, 0xdb, 0xec, 0x9b, 0x79, 0xbc,
	0x7b, 0x78, 0xf7, 0x1c, 0xfd, 0xf0, 0x04, 0x1d, 0x46, 0xd3, 0x9b, 0x70, 0x42, 0xff, 0xf0, 0x83,
	0x69, 0x18, 0xf7, 0x67, 0x69, 0xc2, 0x13, 0xb2, 0x29, 0x16, 0x4e, 0x73, 0x9a, 0x04, 0x34, 0x62,
	0xd2, 0xe8, 0x7a, 0x50, 0x1f, 0x86, 0x11, 0xa7, 0x29, 0xe9, 0xc2, 0xe6, 0x30, 0xa4, 0x51, 0x60,
	0x5b, 0x07, 0xd6, 0x61, 0xc3, 0x93, 0x0b, 0xd2, 0x83, 0xc6, 0xe5, 0x8c, 0xa6, 0x3e, 0x0f, 0x93,
	0xd8, 0xde, 0x10, 0x3b, 0xb9, 0x21, 0x8b, 0x79, 0xe3, 0x47, 0x73, 0x6a, 0xd7, 0x64, 0x8c, 0x58,
	0xb8, 0x7d, 0x80, 0x11, 0xe5, 0x1e, 0xfd, 0x6b, 0x4e, 0x19, 0x27, 0xbb, 0x50, 0xfb, 0x95, 0xfe,
	0x8d, 0xa8, 0xd9, 0x4f, 0xd2, 0x86, 0x8d, 0xf3, 0x33, 0x04, 0xdb, 0x38, 0x3f, 0x73, 0x6f, 0x60,
	0xe7, 0x22, 0x64, 0x2b, 0x02, 0xbe, 0x83, 0xed, 0xcc, 0xe1, 0x72, 0xc6, 0x99, 0x08, 0xdb, 0x39,
	0xde, 0xed, 0x63, 0x15, 0xca, 0xee, 0x69, 0x0f, 0xf2, 0x15, 0x6c, 0xc9, 0x92, 0x98, 0x5d, 0x3b,
	0xa8, 0x1d, 0xee, 0x1c, 0xb7, 0xfa, 0x92, 0x06, 0x69, 0xf5, 0xd4, 0xae, 0xfb, 0x05, 0xb4, 0x06,
	0xc9, 0x3c, 0xe6, 0x1e, 0x65, 0xb3, 0x24, 0x66, 0x34, 0x2b, 0x47, 0x18, 0xc4, 0xd9, 0x35, 0x4f,
	0x2e, 0xdc, 0x1f, 0xa0, 0x75, 0x46, 0x23, 0xca, 0xe9, 0x87, 0x57, 0xb4, 0x0b, 0x6d, 0x15, 0x22,
	0xa1, 0xdd, 0x6f, 0x00, 0xae, 0x66, 0x51, 0xe2, 0x07, 0x22, 0xc5, 0x1e, 0x34, 0xde, 0xfa, 0x9c,
	0xa6, 0x53, 0x3f, 0xbd, 0x16, 0x38, 0xdb, 0x5e, 0x6e, 0x70, 0xff, 0xb1, 0xa0, 0x25, 0x9d, 0x3f,
	0xf8, 0xc4, 0xbc, 0x7b, 0xb5, 0x62, 0xf7, 0x1c, 0xd8, 0x1e, 0x86, 0x11, 0x8d, 0xfd, 0x29, 0xb5,
	0xef, 0x89, 0x0d, 0xbd, 0x26, 0x36, 0x6c, 0x0d, 0x92, 0x98, 0xd3, 0x98, 0xdb, 0x9b, 0x07, 0xd6,
	0x61, 0xd3, 0x53, 0x4b, 0xf2, 0x48, 0x1d, 0x7f, 0x39, 0xcb, 0xba, 0xcc, 0xec, 0xba, 0xe0, 0xfc,
	0x01, 0xd2, 0x98, 0xd7, 0xe1, 0x95, 0xfd, 0x5c, 0x17, 0xda, 0x2a, 0x6f, 0x64, 0x74, 0x17, 0x6a,
	0x57, 0xde, 0xb9, 0x4a, 0xfc, 0xca, 0x3b, 0x77, 0x27, 0xd0, 0xba, 0x48, 0x92, 0xeb, 0xf9, 0x6c,
	0x79, 0x6d, 0x04, 0xee, 0xfd, 0x46, 0xd3, 0x29, 0x56, 0x27, 0x7e, 0x97, 0xae, 0x40, 0xed, 0xb6,
	0x2b, 0xe0, 0x5e, 0x40, 0x53, 0x1d, 0xc2, 0xe6, 0x11, 0x47, 0xb6, 0xac, 0x22, 0x5b, 0x17, 0xfe,
	0x98, 0x46, 0x78, 0x84, 0x5c, 0x90, 0x87, 0x50, 0x7f, 0xcd, 0x7d, 0x3e, 0x67, 0x48, 0x22, 0xae,
	0xdc, 0x13, 0x68, 0x6b, 0x34, 0x59, 0xd6, 0xb7, 0x50, 0x97, 0xc8, 0xb6, 0x25, 0x6e, 0x58, 0x07,
	0xa9, 0x29, 0x1e, 0xea, 0xa1, 0x8b, 0xfb, 0x16, 0xf6, 0x06, 0x29, 0xf5, 0x39, 0x1d, 0x52, 0x1a,
	0x8c, 0xfd, 0xc9, 0xf5, 0xca, 0x8b, 0xae, 0x9c, 0xaa, 0x17, 0x5d, 0x07, 0x6b, 0x0f, 0x77, 0x08,
	0x0f, 0xab, 0xc0, 0x98, 0x5f, 0x11, 0xc7, 0xba, 0x15, 0x67, 0x00, 0x9d, 0x11, 0xe5, 0x9f, 0x08,
	0x32, 0x82, 0xbd, 0x8c, 0x7e, 0xb5, 0x66, 0x1a, 0xa6, 0x0f, 0x0d, 0x6d, 0x44, 0xba, 0x16, 0x71,
	0x72, 0x97, 0x8c, 0xae, 0xab, 0x59, 0xf0, 0xff, 0xd0, 0x55, 0x05, 0xfe, 0xa8, 0x4a, 0x5f, 0x43,
	0x57, 0xd2, 0xfe, 0x26, 0x64, 0x21, 0x4f, 0xd2, 0xe5, 0xf9, 0x7d, 0x0d, 0x5b, 0xe8, 0x83, 0xe9,
	0xdd, 0x57, 0xb0, 0x2a, 0x54, 0xed, 0xbb, 0x2f, 0xd4, 0x25, 0xd1, 0xa0, 0x98, 0x5b, 0x01, 0xc3,
	0xba, 0x05, 0xe3, 0x14, 0xc8, 0x88, 0xf2, 0x4f, 0x00, 0x18, 0x40, 0x37, 0xeb, 0x21, 0x2e, 0x59,
	0xe1, 0xba, 0x6f, 0x2b, 0x1b, 0x76, 0x70, 0x01, 0x43, 0x3b, 0x64, 0xf4, 0x48, 0x9a, 0xef, 0x98,
	0x9e, 0x0a, 0xe8, 0xfa, 0xd5, 0x5d, 0x42, 0x47, 0x52, 0xec, 0xf9, 0x3c, 0x8c, 0xdf, 0x2f, 0xcf,
	0xeb, 0x4b, 0xa8, 0x4b, 0x17, 0x4c, 0xab, 0xad, 0x20, 0x31, 0x10, 0x77, 0xdd, 0x67, 0xea, 0x22,
	0x28, 0x40, 0xcc, 0x29, 0x8f, 0xb7, 0x56, 0xc6, 0x3f, 0x81, 0x07, 0xd9, 0x3b, 0xf9, 0x71, 0xc1,
	0xa7, 0xd0, 0x11, 0x8f, 0xa6, 0x58, 0xe5, 0xad, 0x3a, 0x84, 0x2d, 0x34, 0x61, 0xa7, 0xaa, 0xf1,
	0x6a, 0x3b, 0xa3, 0x43, 0x52, 0x7a, 0x87, 0x74, 0x94, 0x01, 0xd7, 0xab, 0xe8, 0xf8, 0x5f, 0x80,
	0xcd, 0xe7, 0x99, 0x8c, 0x92, 0x57, 0xd0, 0x2e, 0x0b, 0x1b, 0xe9, 0xa1, 0xc0, 0x1a, 0x85, 0xd4,
	0xf9, 0x7c, 0xc9, 0x2e, 0x26, 0xf0, 0x14, 0x76, 0x0a, 0xfa, 0x46, 0xd4, 0x3b, 0x96, 0xcf, 0x28,
	0x8e, 0x93, 0x9b, 0x16, 0xa2, 0x9f, 0x43, 0xab, 0x24, 0x6c, 0x84, 0x28, 0xb1, 0xcf, 0x67, 0x16,
	0xa7, 0x57, 0xb0, 0x2d, 0x4a, 0xe0, 0x2f, 0xd0, 0x16, 0xa3, 0xc4, 0x6a, 0x8c, 0xae, 0xaa, 0xa2,
	0x34, 0x93, 0xbc, 0xca, 0xde, 0xd4, 0xc0, 0xc4, 0x85, 0x51, 0x25, 0x35, 0x17, 0x4b, 0xa4, 0xee,
	0x44, 0x4d, 0x26, 0x1a, 0x4e, 0x1d, 0x5b, 0x9a, 0x71, 0x9c, 0xbd, 0x8a, 0x15, 0xc3, 0x9f, 0xc1,
	0x7d, 0xf9, 0xc6, 0xe5, 0xa5, 0x74, 0x2b, 0x6f, 0x5f, 0x39, 0xbe, 0xf2, 0x70, 0xbe, 0x84, 0x56,
	0x49, 0xe6, 0xc8, 0x7e, 0xa9, 0x75, 0x65, 0xc9, 0x70, 0x7a, 0xe6, 0x4d, 0xcd, 0x2a, 0xe4, 0x72,
	0x67, 0xea, 0xea, 0x67, 0xb9, 0xa9, 0x1a, 0x7b, 0x0a, 0xcd, 0xa2, 0xd2, 0x19, 0xfb, 0xb1, 0x5f,
	0xb0, 0x2d, 0x48, 0xe2, 0xcf, 0x38, 0x3b, 0xae, 0x44, 0x30, 0x77, 0xf4, 0x65, 0x36, 0x5e, 0x05,
	0x06, 0x0e, 0x4c, 0xb2, 0xe9, 0xf4, 0xcc, 0x9b, 0xfa, 0x6a, 0xe3, 0x6c, 0xaa, 0xb0, 0xd6, 0xea,
	0xa6, 0x1e, 0x6c, 0x74, 0x15, 0x6b, 0x35, 0x73, 0x04, 0xcd, 0xa2, 0xfe, 0x11, 0xa7, 0xd4, 0xae,
	0x92, 0xac, 0x38, 0xfb, 0xc6, 0x3d, 0x04, 0x7a, 0x0c, 0x0d, 0x2d, 0x84, 0xa6, 0x46, 0xda, 0x05,
	0x53, 0x39, 0xf2, 0x04, 0x3f, 0x1d, 0xa4, 0xa6, 0x19, 0x9b, 0xe0, 0x14, 0x6d, 0x15, 0xb5, 0x7c,
	0x0c, 0x4d, 0xd9, 0x9b, 0x15, 0xf1, 0xe6, 0x26, 0x8e, 0xa0, 0x59, 0x14, 0x3b, 0x5d, 0xbb, 0x41,
	0x52, 0x9d, 0x7d, 0xe3, 0x1e, 0x02, 0x3d, 0x81, 0x26, 0x76, 0x45, 0x02, 0xad, 0xd5, 0xc0, 0xa7,
	0x7a, 0x98, 0xc6, 0x02, 0xd6, 0xe9, 0xdf, 0x8b, 0x47, 0xbf, 0xff, 0xf4, 0x3e, 0xe4, 0x7f, 0xce,
	0xc7, 0xfd, 0x49, 0x32, 0x3d, 0x9a, 0xb2, 0x49, 0xea, 0xbf, 0xe3, 0x6c, 0xea, 0xc7, 0x47, 0x01,
	0xbd, 0x99, 0x24, 0xf1, 0xf7, 0xef, 0xf0, 0x4f, 0x7e, 0x84, 0x9f, 0x93, 0xec, 0x48, 0xe0, 0x8c,
	0xeb, 0xe2, 0xdb, 0xf1, 0xc7, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa7, 0x25, 0x9b, 0xf5, 0x67,
	0x0e, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdminClient interface {
	// CreateFeedback allows creation of entity of type Feedback
	CreateFeedback(ctx context.Context, in *CreateFeedbackRequest, opts ...grpc.CallOption) (*CreateFeedbackResponse, error)
	// GetFeedback allows getting a single entity of type Feedback
	GetFeedback(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetFeedbackResponse, error)
	// ListFeedbacks allows listing all entity of type Feedback
	ListFeedbacks(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListFeedbacksResponse, error)
	// CountFeedbacks allows counting the listing all entity of type Feedback
	CountFeedbacks(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*CountResponse, error)
	// UpdateFeedback allows updating one entity of type Feedback
	UpdateFeedback(ctx context.Context, in *UpdateFeedbackRequest, opts ...grpc.CallOption) (*UpdateFeedbackResponse, error)
	// DeleteFeedback allows deleting an entity of type Feedback
	DeleteFeedback(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	LookupFeedbacks(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*LookupResponse, error)
	// CreateVisitor allows creation of entity of type Visitor
	CreateVisitor(ctx context.Context, in *CreateVisitorRequest, opts ...grpc.CallOption) (*CreateVisitorResponse, error)
	// GetVisitor allows getting a single entity of type Visitor
	GetVisitor(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetVisitorResponse, error)
	// ListVisitors allows listing all entity of type Visitor
	ListVisitors(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListVisitorsResponse, error)
	// CountVisitors allows counting the listing all entity of type Visitor
	CountVisitors(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*CountResponse, error)
	// UpdateVisitor allows updating one entity of type Visitor
	UpdateVisitor(ctx context.Context, in *UpdateVisitorRequest, opts ...grpc.CallOption) (*UpdateVisitorResponse, error)
	// DeleteVisitor allows deleting an entity of type Visitor
	DeleteVisitor(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	LookupVisitors(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*LookupResponse, error)
	// CreateRating allows creation of entity of type Rating
	CreateRating(ctx context.Context, in *CreateRatingRequest, opts ...grpc.CallOption) (*CreateRatingResponse, error)
	// GetRating allows getting a single entity of type Rating
	GetRating(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetRatingResponse, error)
	// ListRatings allows listing all entity of type Rating
	ListRatings(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListRatingsResponse, error)
	// CountRatings allows counting the listing all entity of type Rating
	CountRatings(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*CountResponse, error)
	// UpdateRating allows updating one entity of type Rating
	UpdateRating(ctx context.Context, in *UpdateRatingRequest, opts ...grpc.CallOption) (*UpdateRatingResponse, error)
	// DeleteRating allows deleting an entity of type Rating
	DeleteRating(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	LookupRatings(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*LookupResponse, error)
}

type adminClient struct {
	cc *grpc.ClientConn
}

func NewAdminClient(cc *grpc.ClientConn) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) CreateFeedback(ctx context.Context, in *CreateFeedbackRequest, opts ...grpc.CallOption) (*CreateFeedbackResponse, error) {
	out := new(CreateFeedbackResponse)
	err := c.cc.Invoke(ctx, "/admin.Admin/CreateFeedback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetFeedback(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetFeedbackResponse, error) {
	out := new(GetFeedbackResponse)
	err := c.cc.Invoke(ctx, "/admin.Admin/GetFeedback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListFeedbacks(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListFeedbacksResponse, error) {
	out := new(ListFeedbacksResponse)
	err := c.cc.Invoke(ctx, "/admin.Admin/ListFeedbacks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) CountFeedbacks(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*CountResponse, error) {
	out := new(CountResponse)
	err := c.cc.Invoke(ctx, "/admin.Admin/CountFeedbacks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdateFeedback(ctx context.Context, in *UpdateFeedbackRequest, opts ...grpc.CallOption) (*UpdateFeedbackResponse, error) {
	out := new(UpdateFeedbackResponse)
	err := c.cc.Invoke(ctx, "/admin.Admin/UpdateFeedback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) DeleteFeedback(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/admin.Admin/DeleteFeedback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) LookupFeedbacks(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*LookupResponse, error) {
	out := new(LookupResponse)
	err := c.cc.Invoke(ctx, "/admin.Admin/LookupFeedbacks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) CreateVisitor(ctx context.Context, in *CreateVisitorRequest, opts ...grpc.CallOption) (*CreateVisitorResponse, error) {
	out := new(CreateVisitorResponse)
	err := c.cc.Invoke(ctx, "/admin.Admin/CreateVisitor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetVisitor(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetVisitorResponse, error) {
	out := new(GetVisitorResponse)
	err := c.cc.Invoke(ctx, "/admin.Admin/GetVisitor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListVisitors(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListVisitorsResponse, error) {
	out := new(ListVisitorsResponse)
	err := c.cc.Invoke(ctx, "/admin.Admin/ListVisitors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) CountVisitors(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*CountResponse, error) {
	out := new(CountResponse)
	err := c.cc.Invoke(ctx, "/admin.Admin/CountVisitors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdateVisitor(ctx context.Context, in *UpdateVisitorRequest, opts ...grpc.CallOption) (*UpdateVisitorResponse, error) {
	out := new(UpdateVisitorResponse)
	err := c.cc.Invoke(ctx, "/admin.Admin/UpdateVisitor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) DeleteVisitor(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/admin.Admin/DeleteVisitor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) LookupVisitors(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*LookupResponse, error) {
	out := new(LookupResponse)
	err := c.cc.Invoke(ctx, "/admin.Admin/LookupVisitors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) CreateRating(ctx context.Context, in *CreateRatingRequest, opts ...grpc.CallOption) (*CreateRatingResponse, error) {
	out := new(CreateRatingResponse)
	err := c.cc.Invoke(ctx, "/admin.Admin/CreateRating", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetRating(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetRatingResponse, error) {
	out := new(GetRatingResponse)
	err := c.cc.Invoke(ctx, "/admin.Admin/GetRating", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListRatings(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListRatingsResponse, error) {
	out := new(ListRatingsResponse)
	err := c.cc.Invoke(ctx, "/admin.Admin/ListRatings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) CountRatings(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*CountResponse, error) {
	out := new(CountResponse)
	err := c.cc.Invoke(ctx, "/admin.Admin/CountRatings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdateRating(ctx context.Context, in *UpdateRatingRequest, opts ...grpc.CallOption) (*UpdateRatingResponse, error) {
	out := new(UpdateRatingResponse)
	err := c.cc.Invoke(ctx, "/admin.Admin/UpdateRating", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) DeleteRating(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/admin.Admin/DeleteRating", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) LookupRatings(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*LookupResponse, error) {
	out := new(LookupResponse)
	err := c.cc.Invoke(ctx, "/admin.Admin/LookupRatings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServer is the server API for Admin service.
type AdminServer interface {
	// CreateFeedback allows creation of entity of type Feedback
	CreateFeedback(context.Context, *CreateFeedbackRequest) (*CreateFeedbackResponse, error)
	// GetFeedback allows getting a single entity of type Feedback
	GetFeedback(context.Context, *GetRequest) (*GetFeedbackResponse, error)
	// ListFeedbacks allows listing all entity of type Feedback
	ListFeedbacks(context.Context, *ListRequest) (*ListFeedbacksResponse, error)
	// CountFeedbacks allows counting the listing all entity of type Feedback
	CountFeedbacks(context.Context, *ListRequest) (*CountResponse, error)
	// UpdateFeedback allows updating one entity of type Feedback
	UpdateFeedback(context.Context, *UpdateFeedbackRequest) (*UpdateFeedbackResponse, error)
	// DeleteFeedback allows deleting an entity of type Feedback
	DeleteFeedback(context.Context, *DeleteRequest) (*DeleteResponse, error)
	LookupFeedbacks(context.Context, *LookupRequest) (*LookupResponse, error)
	// CreateVisitor allows creation of entity of type Visitor
	CreateVisitor(context.Context, *CreateVisitorRequest) (*CreateVisitorResponse, error)
	// GetVisitor allows getting a single entity of type Visitor
	GetVisitor(context.Context, *GetRequest) (*GetVisitorResponse, error)
	// ListVisitors allows listing all entity of type Visitor
	ListVisitors(context.Context, *ListRequest) (*ListVisitorsResponse, error)
	// CountVisitors allows counting the listing all entity of type Visitor
	CountVisitors(context.Context, *ListRequest) (*CountResponse, error)
	// UpdateVisitor allows updating one entity of type Visitor
	UpdateVisitor(context.Context, *UpdateVisitorRequest) (*UpdateVisitorResponse, error)
	// DeleteVisitor allows deleting an entity of type Visitor
	DeleteVisitor(context.Context, *DeleteRequest) (*DeleteResponse, error)
	LookupVisitors(context.Context, *LookupRequest) (*LookupResponse, error)
	// CreateRating allows creation of entity of type Rating
	CreateRating(context.Context, *CreateRatingRequest) (*CreateRatingResponse, error)
	// GetRating allows getting a single entity of type Rating
	GetRating(context.Context, *GetRequest) (*GetRatingResponse, error)
	// ListRatings allows listing all entity of type Rating
	ListRatings(context.Context, *ListRequest) (*ListRatingsResponse, error)
	// CountRatings allows counting the listing all entity of type Rating
	CountRatings(context.Context, *ListRequest) (*CountResponse, error)
	// UpdateRating allows updating one entity of type Rating
	UpdateRating(context.Context, *UpdateRatingRequest) (*UpdateRatingResponse, error)
	// DeleteRating allows deleting an entity of type Rating
	DeleteRating(context.Context, *DeleteRequest) (*DeleteResponse, error)
	LookupRatings(context.Context, *LookupRequest) (*LookupResponse, error)
}

func RegisterAdminServer(s *grpc.Server, srv AdminServer) {
	s.RegisterService(&_Admin_serviceDesc, srv)
}

func _Admin_CreateFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).CreateFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.Admin/CreateFeedback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).CreateFeedback(ctx, req.(*CreateFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.Admin/GetFeedback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetFeedback(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListFeedbacks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListFeedbacks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.Admin/ListFeedbacks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListFeedbacks(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_CountFeedbacks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).CountFeedbacks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.Admin/CountFeedbacks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).CountFeedbacks(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdateFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdateFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.Admin/UpdateFeedback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdateFeedback(ctx, req.(*UpdateFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_DeleteFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).DeleteFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.Admin/DeleteFeedback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).DeleteFeedback(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_LookupFeedbacks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).LookupFeedbacks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.Admin/LookupFeedbacks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).LookupFeedbacks(ctx, req.(*LookupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_CreateVisitor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVisitorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).CreateVisitor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.Admin/CreateVisitor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).CreateVisitor(ctx, req.(*CreateVisitorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetVisitor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetVisitor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.Admin/GetVisitor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetVisitor(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListVisitors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListVisitors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.Admin/ListVisitors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListVisitors(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_CountVisitors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).CountVisitors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.Admin/CountVisitors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).CountVisitors(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdateVisitor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVisitorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdateVisitor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.Admin/UpdateVisitor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdateVisitor(ctx, req.(*UpdateVisitorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_DeleteVisitor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).DeleteVisitor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.Admin/DeleteVisitor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).DeleteVisitor(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_LookupVisitors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).LookupVisitors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.Admin/LookupVisitors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).LookupVisitors(ctx, req.(*LookupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_CreateRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).CreateRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.Admin/CreateRating",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).CreateRating(ctx, req.(*CreateRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.Admin/GetRating",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetRating(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListRatings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListRatings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.Admin/ListRatings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListRatings(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_CountRatings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).CountRatings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.Admin/CountRatings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).CountRatings(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdateRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdateRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.Admin/UpdateRating",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdateRating(ctx, req.(*UpdateRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_DeleteRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).DeleteRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.Admin/DeleteRating",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).DeleteRating(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_LookupRatings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).LookupRatings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.Admin/LookupRatings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).LookupRatings(ctx, req.(*LookupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Admin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "admin.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFeedback",
			Handler:    _Admin_CreateFeedback_Handler,
		},
		{
			MethodName: "GetFeedback",
			Handler:    _Admin_GetFeedback_Handler,
		},
		{
			MethodName: "ListFeedbacks",
			Handler:    _Admin_ListFeedbacks_Handler,
		},
		{
			MethodName: "CountFeedbacks",
			Handler:    _Admin_CountFeedbacks_Handler,
		},
		{
			MethodName: "UpdateFeedback",
			Handler:    _Admin_UpdateFeedback_Handler,
		},
		{
			MethodName: "DeleteFeedback",
			Handler:    _Admin_DeleteFeedback_Handler,
		},
		{
			MethodName: "LookupFeedbacks",
			Handler:    _Admin_LookupFeedbacks_Handler,
		},
		{
			MethodName: "CreateVisitor",
			Handler:    _Admin_CreateVisitor_Handler,
		},
		{
			MethodName: "GetVisitor",
			Handler:    _Admin_GetVisitor_Handler,
		},
		{
			MethodName: "ListVisitors",
			Handler:    _Admin_ListVisitors_Handler,
		},
		{
			MethodName: "CountVisitors",
			Handler:    _Admin_CountVisitors_Handler,
		},
		{
			MethodName: "UpdateVisitor",
			Handler:    _Admin_UpdateVisitor_Handler,
		},
		{
			MethodName: "DeleteVisitor",
			Handler:    _Admin_DeleteVisitor_Handler,
		},
		{
			MethodName: "LookupVisitors",
			Handler:    _Admin_LookupVisitors_Handler,
		},
		{
			MethodName: "CreateRating",
			Handler:    _Admin_CreateRating_Handler,
		},
		{
			MethodName: "GetRating",
			Handler:    _Admin_GetRating_Handler,
		},
		{
			MethodName: "ListRatings",
			Handler:    _Admin_ListRatings_Handler,
		},
		{
			MethodName: "CountRatings",
			Handler:    _Admin_CountRatings_Handler,
		},
		{
			MethodName: "UpdateRating",
			Handler:    _Admin_UpdateRating_Handler,
		},
		{
			MethodName: "DeleteRating",
			Handler:    _Admin_DeleteRating_Handler,
		},
		{
			MethodName: "LookupRatings",
			Handler:    _Admin_LookupRatings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_admin.proto",
}
