// generated by gocipe 98d04eff905d6c25e0ba7946b5abe59ef772bba989a56cb131b63b92b50cf33b; DO NOT EDIT

package visitor

// Visitor represents a conference visitor
type Visitor struct {
	ID        *string `json:"id"`
	Name      *string `json:"name"`
	PhotoLink *string `json:"photo_link"`
}

// New returns an instance of Visitor
func New() *Visitor {
	return &Visitor{
		ID:        new(string),
		Name:      new(string),
		PhotoLink: new(string),
	}
}
