// generated by gocipe de1bb85c9a7bb2a94d27bdc90a816fda2f0c1a74eedc651da8880ddade0f7a18; DO NOT EDIT

package visitor

// Visitor represents a conference visitor
type Visitor struct {
	ID        *string `json:"id"`
	Name      *string `json:"name"`
	PhotoLink *string `json:"photo_link"`
	Status    *bool   `json:"status"`
}

// New returns an instance of Visitor
func New() *Visitor {
	return &Visitor{
		ID:        new(string),
		Name:      new(string),
		PhotoLink: new(string),
		Status:    new(bool),
	}
}
