// generated by gocipe 7024126c5667f01762364d56ce1e35bbbebe5543247abb9a7edcb6ee359cef12; DO NOT EDIT

package visitor

// Visitor represents a conference visitor
type Visitor struct {
	ID        *int64  `json:"id"`
	Name      *string `json:"name"`
	MeetupID  *int    `json:"meetup_id"`
	PhotoLink *string `json:"photo_link"`
}

// New returns an instance of Visitor
func New() *Visitor {
	return &Visitor{
		ID:        new(int64),
		Name:      new(string),
		MeetupID:  new(int),
		PhotoLink: new(string),
	}
}
