// generated by gocipe 2e5ed5d4d943c424d9e2d746f06bc60d148cc25203f3693488ed10ba23c0d12a; DO NOT EDIT

package visitor

import (
	"github.com/gorilla/mux"
)

type responseSingle struct {
	Status   bool      `json:"status"`
	Messages []message `json:"messages"`
	Entity   *Visitor  `json:"entity"`
}

type responseList struct {
	Status   bool       `json:"status"`
	Messages []message  `json:"messages"`
	Entities []*Visitor `json:"entities"`
}

type message struct {
	Type    rune   `json:"type"`
	Message string `json:"message"`
}

//RegisterRoutes registers routes with a mux Router
func RegisterRoutes(router *mux.Router) {

}
