// generated by gocipe 8711bda2250e6c55fba92576b5a3047c42d034e6742f4bff5ae1f9e546907463; DO NOT EDIT

package visitor

import (
	"database/sql"
	"errors"
	"fmt"
	"strconv"
	"strings"

	"github.com/mscraftsman/devcon-feedback/models"
)

var db *sql.DB

// Inject allows injection of services into the package
func Inject(database *sql.DB) {
	db = database
}

// Get returns a single Visitor from database by primary key
func Get(id string) (*Visitor, error) {
	var entity = New()

	if err := crudPreGet(id); err != nil {
		return nil, fmt.Errorf("error executing crudPreGet() in Get(%x) for entity 'Visitor': %s", id, err)
	}

	rows, err := db.Query("SELECT t.name, t.photo_link FROM visitors t WHERE id = $1 ORDER BY t.id ASC", id)
	if err != nil {
		return nil, err
	}

	defer rows.Close()
	for rows.Next() {

		err := rows.Scan(entity.Name, entity.PhotoLink)
		if err != nil {
			return nil, err
		}

	}

	if err = crudPostGet(entity); err != nil {
		return nil, fmt.Errorf("error executing crudPostGet() in Get(%x) for entity 'Visitor': %s", id, err)
	}

	return entity, nil
}

// List returns a slice containing Visitor records
func List(filters []models.ListFilter) ([]*Visitor, error) {
	var (
		list     []*Visitor
		segments []string
		values   []interface{}
		err      error
	)

	query := "SELECT t.name, t.photo_link FROM visitors"

	if filters, err = crudPreList(filters); err != nil {
		return nil, fmt.Errorf("error executing crudPreList() in List(filters) for entity 'Visitor': %s", err)
	}

	for i, filter := range filters {
		segments = append(segments, filter.Field+" "+filter.Operation+" $"+strconv.Itoa(i+1))
		values = append(values, filter.Value)
	}

	if len(segments) != 0 {
		query += " WHERE " + strings.Join(segments, " AND ")
	}

	rows, err := db.Query(query+" ORDER BY id ASC", values...)

	if err != nil {
		return nil, err
	}

	defer rows.Close()
	for rows.Next() {
		entity := New()
		err := rows.Scan(entity.Name, entity.PhotoLink)
		if err != nil {
			return nil, err
		}

		list = append(list, entity)

	}

	if list, err = crudPostList(list); err != nil {
		return nil, fmt.Errorf("error executing crudPostList() in List(filters) for entity 'Visitor': %s", err)
	}

	return list, nil
}

// Delete deletes a Visitor record from database by id primary key
func Delete(id string, tx *sql.Tx, autocommit bool) error {
	var (
		err error
	)

	if tx == nil {
		tx, err = db.Begin()
		if err != nil {
			return err
		}
	}

	stmt, err := tx.Prepare("DELETE FROM visitors WHERE id = $1")
	if err != nil {
		return err
	}

	if err := crudPreDelete(id, tx); err != nil {
		tx.Rollback()
		return fmt.Errorf("error executing crudPreDelete() in Delete(%x) for entity 'Visitor': %s", id, err)
	}

	_, err = stmt.Exec(id)
	if err != nil {
		tx.Rollback()
		return fmt.Errorf("error executing transaction statement in Delete(%x) for entity 'Visitor': %s", id, err)
	}

	if err := crudPostDelete(id, tx); err != nil {
		tx.Rollback()
		return fmt.Errorf("Error executing crudPostDelete() in Delete(%x) for entity 'Visitor': %s", id, err)
	}

	if autocommit {
		err = tx.Commit()
		if err != nil {
			return fmt.Errorf("error committing transaction in Delete(%x) for 'Visitor': %s", id, err)
		}
	}

	return err
}

// Delete deletes a Visitor record from database and sets id to nil
func (entity *Visitor) Delete(tx *sql.Tx, autocommit bool) error {
	var (
		err error
	)

	id := *entity.ID

	if tx == nil {
		tx, err = db.Begin()
		if err != nil {
			return err
		}
	}

	stmt, err := tx.Prepare("DELETE FROM visitors WHERE id = $1")
	if err != nil {
		return err
	}

	if err := crudPreDelete(id, tx); err != nil {
		tx.Rollback()
		return fmt.Errorf("error executing crudPreDelete() in Visitor.Delete() for ID = %x : %s", id, err)
	}

	_, err = stmt.Exec(id)
	if err == nil {
		entity.ID = nil
	} else {
		tx.Rollback()
		return fmt.Errorf("error executing transaction statement in Visitor.Delete() for ID = %x : %s", id, err)
	}

	if err = crudPostDelete(id, tx); err != nil {
		tx.Rollback()
		return fmt.Errorf("error executing crudPostDelete() in Visitor.Delete() for ID = %x : %s", id, err)
	}

	if autocommit {
		err = tx.Commit()
		if err != nil {
			return fmt.Errorf("error committing transaction in Visitor.Delete() for ID = %x : %s", id, err)
		}
	}

	return err
}

// Save either inserts or updates a Visitor record based on whether or not id is nil
func (entity *Visitor) Save(tx *sql.Tx, autocommit bool) error {
	if entity.ID == nil {
		return errors.New("primary key cannot be nil")
	}
	return entity.Merge(tx, autocommit)
}

// Insert performs an SQL insert for Visitor record and update instance with inserted id.
func (entity *Visitor) Insert(tx *sql.Tx, autocommit bool) error {
	var (
		err error
	)

	if tx == nil {
		tx, err = db.Begin()
		if err != nil {
			return err
		}
	}

	stmt, err := tx.Prepare("INSERT INTO visitors (id, name, photo_link) VALUES ($1, $2, $3)")
	if err != nil {
		return err
	}

	if err := crudPreSave("INSERT", entity, tx); err != nil {
		tx.Rollback()
		return fmt.Errorf("error executing crudPreSave() in Visitor.Insert(): %s", err)
	}

	_, err = stmt.Exec(*entity.ID, *entity.Name, *entity.PhotoLink)
	if err != nil {
		tx.Rollback()
		return fmt.Errorf("error executing transaction statement in Visitor: %s", err)
	}

	if err := crudPostSave("INSERT", entity, tx); err != nil {
		tx.Rollback()
		return fmt.Errorf("error executing crudPostSave() in Visitor.Insert(): %s", err)
	}

	if autocommit {
		err = tx.Commit()
		if err != nil {
			return fmt.Errorf("error committing transaction in Visitor.Insert(): %s", err)
		}
	}

	return nil
}

// Update Will execute an SQLUpdate Statement for Visitor in the database. Prefer using Save instead of Update directly.
func (entity *Visitor) Update(tx *sql.Tx, autocommit bool) error {
	var (
		err error
	)

	if tx == nil {
		tx, err = db.Begin()
		if err != nil {
			return err
		}
	}

	stmt, err := tx.Prepare("UPDATE visitors SET name = $2, photo_link = $3 WHERE id = $1")
	if err != nil {
		return err
	}

	if err := crudPreSave("UPDATE", entity, tx); err != nil {
		tx.Rollback()
		return fmt.Errorf("error executing crudPreSave() in Visitor.Update(): %s", err)
	}

	_, err = stmt.Exec(*entity.Name, *entity.PhotoLink)
	if err != nil {
		tx.Rollback()
		return fmt.Errorf("error executing transaction statement in Visitor.Update(): %s", err)
	}

	if err := crudPostSave("UPDATE", entity, tx); err != nil {
		tx.Rollback()
		return fmt.Errorf("error executing crudPostSave() in Visitor.Update(): %s", err)
	}

	if autocommit {
		err = tx.Commit()
		if err != nil {
			return fmt.Errorf("error committing transaction in Visitor.Update(): %s", err)
		}
	}

	return nil
}

// Merge performs an SQL merge for Visitor record.
func (entity *Visitor) Merge(tx *sql.Tx, autocommit bool) error {
	var (
		err error
	)

	if tx == nil {
		tx, err = db.Begin()
		if err != nil {
			return err
		}
	}

	if entity.ID == nil {
		return entity.Insert(tx, autocommit)
	}

	stmt, err := tx.Prepare(`INSERT INTO visitors (id, name, photo_link) VALUES ($1, $2, $3) 
	ON CONFLICT visitors_pkey UPDATE visitors SET name = $2, photo_link = $3 WHERE id = $1`)
	if err != nil {
		return err
	}

	if err := crudPreSave("MERGE", entity, tx); err != nil {
		tx.Rollback()
		return fmt.Errorf("error executing crudPreSave() in Visitor.Merge(): %s", err)
	}

	_, err = stmt.Exec(*entity.Name, *entity.PhotoLink)
	if err != nil {
		tx.Rollback()
		return fmt.Errorf("error executing transaction statement in Visitor: %s", err)
	}

	if err := crudPostSave("MERGE", entity, tx); err != nil {
		tx.Rollback()
		return fmt.Errorf("error executing crudPostSave() in Visitor.Merge(): %s", err)
	}

	if autocommit {
		err = tx.Commit()
		if err != nil {
			return fmt.Errorf("error committing transaction in Visitor.Merge(): %s", err)
		}
	}

	return nil
}
