// generated by gocipe 8711bda2250e6c55fba92576b5a3047c42d034e6742f4bff5ae1f9e546907463; DO NOT EDIT

package session

import "time"

// Session represents a conference session
type Session struct {
	ID          *string    `json:"id"`
	Title       *string    `json:"title"`
	Description *string    `json:"description"`
	Level       *string    `json:"level"`
	Language    *string    `json:"language"`
	Format      *string    `json:"format"`
	Room        *string    `json:"room"`
	Speakers    *string    `json:"speakers"`
	StartAt     *time.Time `json:"start_at"`
	EndAt       *time.Time `json:"end_at"`
	Status      *bool      `json:"status"`
}

// New returns an instance of Session
func New() *Session {
	return &Session{
		ID:          new(string),
		Title:       new(string),
		Description: new(string),
		Level:       new(string),
		Language:    new(string),
		Format:      new(string),
		Room:        new(string),
		Speakers:    new(string),
		StartAt:     new(time.Time),
		EndAt:       new(time.Time),
		Status:      new(bool),
	}
}
