// generated by gocipe 2e5ed5d4d943c424d9e2d746f06bc60d148cc25203f3693488ed10ba23c0d12a; DO NOT EDIT

package session

import "time"

// Session represents a conference session
type Session struct {
	ID          *string    `json:"id"`
	Title       *string    `json:"title"`
	Description *string    `json:"description"`
	Level       *string    `json:"level"`
	Language    *string    `json:"language"`
	Format      *string    `json:"format"`
	Room        *string    `json:"room"`
	Speakers    *string    `json:"speakers"`
	StartAt     *time.Time `json:"start_at"`
	EndAt       *time.Time `json:"end_at"`
	Status      *bool      `json:"status"`
}

// New returns an instance of Session
func New() *Session {
	return &Session{
		ID:          new(string),
		Title:       new(string),
		Description: new(string),
		Level:       new(string),
		Language:    new(string),
		Format:      new(string),
		Room:        new(string),
		Speakers:    new(string),
		StartAt:     new(time.Time),
		EndAt:       new(time.Time),
		Status:      new(bool),
	}
}
