// generated by gocipe 8711bda2250e6c55fba92576b5a3047c42d034e6742f4bff5ae1f9e546907463; DO NOT EDIT

package session

import (
	"database/sql"
	"errors"
	"fmt"
	"strconv"
	"strings"

	"github.com/mscraftsman/devcon-feedback/models"
)

var db *sql.DB

// Inject allows injection of services into the package
func Inject(database *sql.DB) {
	db = database
}

// Get returns a single Session from database by primary key
func Get(id string) (*Session, error) {
	var entity = New()

	if err := crudPreGet(id); err != nil {
		return nil, fmt.Errorf("error executing crudPreGet() in Get(%x) for entity 'Session': %s", id, err)
	}

	rows, err := db.Query("SELECT t.title, t.description, t.level, t.language, t.format, t.room, t.speakers, t.start_at, t.end_at, t.status FROM sessions t WHERE id = $1 ORDER BY t.id ASC", id)
	if err != nil {
		return nil, err
	}

	defer rows.Close()
	for rows.Next() {

		err := rows.Scan(entity.Title, entity.Description, entity.Level, entity.Language, entity.Format, entity.Room, entity.Speakers, entity.StartAt, entity.EndAt, entity.Status)
		if err != nil {
			return nil, err
		}

	}

	if err = crudPostGet(entity); err != nil {
		return nil, fmt.Errorf("error executing crudPostGet() in Get(%x) for entity 'Session': %s", id, err)
	}

	return entity, nil
}

// List returns a slice containing Session records
func List(filters []models.ListFilter) ([]*Session, error) {
	var (
		list     []*Session
		segments []string
		values   []interface{}
		err      error
	)

	query := "SELECT t.title, t.description, t.level, t.language, t.format, t.room, t.speakers, t.start_at, t.end_at, t.status FROM sessions"

	if filters, err = crudPreList(filters); err != nil {
		return nil, fmt.Errorf("error executing crudPreList() in List(filters) for entity 'Session': %s", err)
	}

	for i, filter := range filters {
		segments = append(segments, filter.Field+" "+filter.Operation+" $"+strconv.Itoa(i+1))
		values = append(values, filter.Value)
	}

	if len(segments) != 0 {
		query += " WHERE " + strings.Join(segments, " AND ")
	}

	rows, err := db.Query(query+" ORDER BY id ASC", values...)

	if err != nil {
		return nil, err
	}

	defer rows.Close()
	for rows.Next() {
		entity := New()
		err := rows.Scan(entity.Title, entity.Description, entity.Level, entity.Language, entity.Format, entity.Room, entity.Speakers, entity.StartAt, entity.EndAt, entity.Status)
		if err != nil {
			return nil, err
		}

		list = append(list, entity)

	}

	if list, err = crudPostList(list); err != nil {
		return nil, fmt.Errorf("error executing crudPostList() in List(filters) for entity 'Session': %s", err)
	}

	return list, nil
}

// Delete deletes a Session record from database by id primary key
func Delete(id string, tx *sql.Tx, autocommit bool) error {
	var (
		err error
	)

	if tx == nil {
		tx, err = db.Begin()
		if err != nil {
			return err
		}
	}

	stmt, err := tx.Prepare("DELETE FROM sessions WHERE id = $1")
	if err != nil {
		return err
	}

	if err := crudPreDelete(id, tx); err != nil {
		tx.Rollback()
		return fmt.Errorf("error executing crudPreDelete() in Delete(%x) for entity 'Session': %s", id, err)
	}

	_, err = stmt.Exec(id)
	if err != nil {
		tx.Rollback()
		return fmt.Errorf("error executing transaction statement in Delete(%x) for entity 'Session': %s", id, err)
	}

	if err := crudPostDelete(id, tx); err != nil {
		tx.Rollback()
		return fmt.Errorf("Error executing crudPostDelete() in Delete(%x) for entity 'Session': %s", id, err)
	}

	if autocommit {
		err = tx.Commit()
		if err != nil {
			return fmt.Errorf("error committing transaction in Delete(%x) for 'Session': %s", id, err)
		}
	}

	return err
}

// Delete deletes a Session record from database and sets id to nil
func (entity *Session) Delete(tx *sql.Tx, autocommit bool) error {
	var (
		err error
	)

	id := *entity.ID

	if tx == nil {
		tx, err = db.Begin()
		if err != nil {
			return err
		}
	}

	stmt, err := tx.Prepare("DELETE FROM sessions WHERE id = $1")
	if err != nil {
		return err
	}

	if err := crudPreDelete(id, tx); err != nil {
		tx.Rollback()
		return fmt.Errorf("error executing crudPreDelete() in Session.Delete() for ID = %x : %s", id, err)
	}

	_, err = stmt.Exec(id)
	if err == nil {
		entity.ID = nil
	} else {
		tx.Rollback()
		return fmt.Errorf("error executing transaction statement in Session.Delete() for ID = %x : %s", id, err)
	}

	if err = crudPostDelete(id, tx); err != nil {
		tx.Rollback()
		return fmt.Errorf("error executing crudPostDelete() in Session.Delete() for ID = %x : %s", id, err)
	}

	if autocommit {
		err = tx.Commit()
		if err != nil {
			return fmt.Errorf("error committing transaction in Session.Delete() for ID = %x : %s", id, err)
		}
	}

	return err
}

// Save either inserts or updates a Session record based on whether or not id is nil
func (entity *Session) Save(tx *sql.Tx, autocommit bool) error {
	if entity.ID == nil {
		return errors.New("primary key cannot be nil")
	}
	return entity.Merge(tx, autocommit)
}

// Insert performs an SQL insert for Session record and update instance with inserted id.
func (entity *Session) Insert(tx *sql.Tx, autocommit bool) error {
	var (
		err error
	)

	if tx == nil {
		tx, err = db.Begin()
		if err != nil {
			return err
		}
	}

	stmt, err := tx.Prepare("INSERT INTO sessions (id, title, description, level, language, format, room, speakers, start_at, end_at, status) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)")
	if err != nil {
		return err
	}

	if err := crudPreSave("INSERT", entity, tx); err != nil {
		tx.Rollback()
		return fmt.Errorf("error executing crudPreSave() in Session.Insert(): %s", err)
	}

	_, err = stmt.Exec(*entity.ID, *entity.Title, *entity.Description, *entity.Level, *entity.Language, *entity.Format, *entity.Room, *entity.Speakers, *entity.StartAt, *entity.EndAt, *entity.Status)
	if err != nil {
		tx.Rollback()
		return fmt.Errorf("error executing transaction statement in Session: %s", err)
	}

	if err := crudPostSave("INSERT", entity, tx); err != nil {
		tx.Rollback()
		return fmt.Errorf("error executing crudPostSave() in Session.Insert(): %s", err)
	}

	if autocommit {
		err = tx.Commit()
		if err != nil {
			return fmt.Errorf("error committing transaction in Session.Insert(): %s", err)
		}
	}

	return nil
}

// Update Will execute an SQLUpdate Statement for Session in the database. Prefer using Save instead of Update directly.
func (entity *Session) Update(tx *sql.Tx, autocommit bool) error {
	var (
		err error
	)

	if tx == nil {
		tx, err = db.Begin()
		if err != nil {
			return err
		}
	}

	stmt, err := tx.Prepare("UPDATE sessions SET title = $2, description = $3, level = $4, language = $5, format = $6, room = $7, speakers = $8, start_at = $9, end_at = $10, status = $11 WHERE id = $1")
	if err != nil {
		return err
	}

	if err := crudPreSave("UPDATE", entity, tx); err != nil {
		tx.Rollback()
		return fmt.Errorf("error executing crudPreSave() in Session.Update(): %s", err)
	}

	_, err = stmt.Exec(*entity.Title, *entity.Description, *entity.Level, *entity.Language, *entity.Format, *entity.Room, *entity.Speakers, *entity.StartAt, *entity.EndAt, *entity.Status)
	if err != nil {
		tx.Rollback()
		return fmt.Errorf("error executing transaction statement in Session.Update(): %s", err)
	}

	if err := crudPostSave("UPDATE", entity, tx); err != nil {
		tx.Rollback()
		return fmt.Errorf("error executing crudPostSave() in Session.Update(): %s", err)
	}

	if autocommit {
		err = tx.Commit()
		if err != nil {
			return fmt.Errorf("error committing transaction in Session.Update(): %s", err)
		}
	}

	return nil
}

// Merge performs an SQL merge for Session record.
func (entity *Session) Merge(tx *sql.Tx, autocommit bool) error {
	var (
		err error
	)

	if tx == nil {
		tx, err = db.Begin()
		if err != nil {
			return err
		}
	}

	if entity.ID == nil {
		return entity.Insert(tx, autocommit)
	}

	stmt, err := tx.Prepare(`INSERT INTO sessions (id, title, description, level, language, format, room, speakers, start_at, end_at, status) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) 
	ON CONFLICT sessions_pkey UPDATE sessions SET title = $2, description = $3, level = $4, language = $5, format = $6, room = $7, speakers = $8, start_at = $9, end_at = $10, status = $11 WHERE id = $1`)
	if err != nil {
		return err
	}

	if err := crudPreSave("MERGE", entity, tx); err != nil {
		tx.Rollback()
		return fmt.Errorf("error executing crudPreSave() in Session.Merge(): %s", err)
	}

	_, err = stmt.Exec(*entity.Title, *entity.Description, *entity.Level, *entity.Language, *entity.Format, *entity.Room, *entity.Speakers, *entity.StartAt, *entity.EndAt, *entity.Status)
	if err != nil {
		tx.Rollback()
		return fmt.Errorf("error executing transaction statement in Session: %s", err)
	}

	if err := crudPostSave("MERGE", entity, tx); err != nil {
		tx.Rollback()
		return fmt.Errorf("error executing crudPostSave() in Session.Merge(): %s", err)
	}

	if autocommit {
		err = tx.Commit()
		if err != nil {
			return fmt.Errorf("error committing transaction in Session.Merge(): %s", err)
		}
	}

	return nil
}
