// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service_data.proto

package data

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	models "github.com/mscraftsman/devcon-feedback/models"
	admin "github.com/mscraftsman/devcon-feedback/services/admin"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// GetByIDRequest represents a request to allow getting a single entity by ID
type GetByIDRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	ID                   string   `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByIDRequest) Reset()         { *m = GetByIDRequest{} }
func (m *GetByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetByIDRequest) ProtoMessage()    {}
func (*GetByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8da69d9277c36882, []int{0}
}

func (m *GetByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByIDRequest.Unmarshal(m, b)
}
func (m *GetByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByIDRequest.Merge(m, src)
}
func (m *GetByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetByIDRequest.Size(m)
}
func (m *GetByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByIDRequest proto.InternalMessageInfo

func (m *GetByIDRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetByIDRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

// GetBySlugRequest represents a request to allow getting a single entity by slug
type GetBySlugRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Slug                 string   `protobuf:"bytes,2,opt,name=Slug,proto3" json:"Slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBySlugRequest) Reset()         { *m = GetBySlugRequest{} }
func (m *GetBySlugRequest) String() string { return proto.CompactTextString(m) }
func (*GetBySlugRequest) ProtoMessage()    {}
func (*GetBySlugRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8da69d9277c36882, []int{1}
}

func (m *GetBySlugRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBySlugRequest.Unmarshal(m, b)
}
func (m *GetBySlugRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBySlugRequest.Marshal(b, m, deterministic)
}
func (m *GetBySlugRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBySlugRequest.Merge(m, src)
}
func (m *GetBySlugRequest) XXX_Size() int {
	return xxx_messageInfo_GetBySlugRequest.Size(m)
}
func (m *GetBySlugRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBySlugRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBySlugRequest proto.InternalMessageInfo

func (m *GetBySlugRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetBySlugRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

// ListRequest represents a request to allow listing of entities
type ListRequest struct {
	Key                  string           `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	ListOpts             *models.ListOpts `protobuf:"bytes,2,opt,name=ListOpts,proto3" json:"ListOpts,omitempty"`
	Filters              []*admin.Filter  `protobuf:"bytes,3,rep,name=Filters,proto3" json:"Filters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8da69d9277c36882, []int{2}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ListRequest) GetListOpts() *models.ListOpts {
	if m != nil {
		return m.ListOpts
	}
	return nil
}

func (m *ListRequest) GetFilters() []*admin.Filter {
	if m != nil {
		return m.Filters
	}
	return nil
}

// TimestampResponse
type TimestampResponse struct {
	ModifiedAt           *timestamp.Timestamp `protobuf:"bytes,1,opt,name=ModifiedAt,proto3" json:"ModifiedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TimestampResponse) Reset()         { *m = TimestampResponse{} }
func (m *TimestampResponse) String() string { return proto.CompactTextString(m) }
func (*TimestampResponse) ProtoMessage()    {}
func (*TimestampResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8da69d9277c36882, []int{3}
}

func (m *TimestampResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimestampResponse.Unmarshal(m, b)
}
func (m *TimestampResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimestampResponse.Marshal(b, m, deterministic)
}
func (m *TimestampResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimestampResponse.Merge(m, src)
}
func (m *TimestampResponse) XXX_Size() int {
	return xxx_messageInfo_TimestampResponse.Size(m)
}
func (m *TimestampResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TimestampResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TimestampResponse proto.InternalMessageInfo

func (m *TimestampResponse) GetModifiedAt() *timestamp.Timestamp {
	if m != nil {
		return m.ModifiedAt
	}
	return nil
}

// FeedbackResponse represents result to a GetByIDRequest or GetBySlugRequest
type FeedbackResponse struct {
	Feedback             *models.Feedback `protobuf:"bytes,1,opt,name=Feedback,proto3" json:"Feedback,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *FeedbackResponse) Reset()         { *m = FeedbackResponse{} }
func (m *FeedbackResponse) String() string { return proto.CompactTextString(m) }
func (*FeedbackResponse) ProtoMessage()    {}
func (*FeedbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8da69d9277c36882, []int{4}
}

func (m *FeedbackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedbackResponse.Unmarshal(m, b)
}
func (m *FeedbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedbackResponse.Marshal(b, m, deterministic)
}
func (m *FeedbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedbackResponse.Merge(m, src)
}
func (m *FeedbackResponse) XXX_Size() int {
	return xxx_messageInfo_FeedbackResponse.Size(m)
}
func (m *FeedbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FeedbackResponse proto.InternalMessageInfo

func (m *FeedbackResponse) GetFeedback() *models.Feedback {
	if m != nil {
		return m.Feedback
	}
	return nil
}

// ListFeedbacksResponse represents result to a ListRequest
type ListFeedbacksResponse struct {
	Feedbacks            []*models.Feedback `protobuf:"bytes,1,rep,name=Feedbacks,proto3" json:"Feedbacks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ListFeedbacksResponse) Reset()         { *m = ListFeedbacksResponse{} }
func (m *ListFeedbacksResponse) String() string { return proto.CompactTextString(m) }
func (*ListFeedbacksResponse) ProtoMessage()    {}
func (*ListFeedbacksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8da69d9277c36882, []int{5}
}

func (m *ListFeedbacksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFeedbacksResponse.Unmarshal(m, b)
}
func (m *ListFeedbacksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFeedbacksResponse.Marshal(b, m, deterministic)
}
func (m *ListFeedbacksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFeedbacksResponse.Merge(m, src)
}
func (m *ListFeedbacksResponse) XXX_Size() int {
	return xxx_messageInfo_ListFeedbacksResponse.Size(m)
}
func (m *ListFeedbacksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFeedbacksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListFeedbacksResponse proto.InternalMessageInfo

func (m *ListFeedbacksResponse) GetFeedbacks() []*models.Feedback {
	if m != nil {
		return m.Feedbacks
	}
	return nil
}

// VisitorResponse represents result to a GetByIDRequest or GetBySlugRequest
type VisitorResponse struct {
	Visitor              *models.Visitor `protobuf:"bytes,1,opt,name=Visitor,proto3" json:"Visitor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *VisitorResponse) Reset()         { *m = VisitorResponse{} }
func (m *VisitorResponse) String() string { return proto.CompactTextString(m) }
func (*VisitorResponse) ProtoMessage()    {}
func (*VisitorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8da69d9277c36882, []int{6}
}

func (m *VisitorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisitorResponse.Unmarshal(m, b)
}
func (m *VisitorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisitorResponse.Marshal(b, m, deterministic)
}
func (m *VisitorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisitorResponse.Merge(m, src)
}
func (m *VisitorResponse) XXX_Size() int {
	return xxx_messageInfo_VisitorResponse.Size(m)
}
func (m *VisitorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VisitorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VisitorResponse proto.InternalMessageInfo

func (m *VisitorResponse) GetVisitor() *models.Visitor {
	if m != nil {
		return m.Visitor
	}
	return nil
}

// ListVisitorsResponse represents result to a ListRequest
type ListVisitorsResponse struct {
	Visitors             []*models.Visitor `protobuf:"bytes,1,rep,name=Visitors,proto3" json:"Visitors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListVisitorsResponse) Reset()         { *m = ListVisitorsResponse{} }
func (m *ListVisitorsResponse) String() string { return proto.CompactTextString(m) }
func (*ListVisitorsResponse) ProtoMessage()    {}
func (*ListVisitorsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8da69d9277c36882, []int{7}
}

func (m *ListVisitorsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListVisitorsResponse.Unmarshal(m, b)
}
func (m *ListVisitorsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListVisitorsResponse.Marshal(b, m, deterministic)
}
func (m *ListVisitorsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListVisitorsResponse.Merge(m, src)
}
func (m *ListVisitorsResponse) XXX_Size() int {
	return xxx_messageInfo_ListVisitorsResponse.Size(m)
}
func (m *ListVisitorsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListVisitorsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListVisitorsResponse proto.InternalMessageInfo

func (m *ListVisitorsResponse) GetVisitors() []*models.Visitor {
	if m != nil {
		return m.Visitors
	}
	return nil
}

// RatingResponse represents result to a GetByIDRequest or GetBySlugRequest
type RatingResponse struct {
	Rating               *models.Rating `protobuf:"bytes,1,opt,name=Rating,proto3" json:"Rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RatingResponse) Reset()         { *m = RatingResponse{} }
func (m *RatingResponse) String() string { return proto.CompactTextString(m) }
func (*RatingResponse) ProtoMessage()    {}
func (*RatingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8da69d9277c36882, []int{8}
}

func (m *RatingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RatingResponse.Unmarshal(m, b)
}
func (m *RatingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RatingResponse.Marshal(b, m, deterministic)
}
func (m *RatingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RatingResponse.Merge(m, src)
}
func (m *RatingResponse) XXX_Size() int {
	return xxx_messageInfo_RatingResponse.Size(m)
}
func (m *RatingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RatingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RatingResponse proto.InternalMessageInfo

func (m *RatingResponse) GetRating() *models.Rating {
	if m != nil {
		return m.Rating
	}
	return nil
}

// ListRatingsResponse represents result to a ListRequest
type ListRatingsResponse struct {
	Ratings              []*models.Rating `protobuf:"bytes,1,rep,name=Ratings,proto3" json:"Ratings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListRatingsResponse) Reset()         { *m = ListRatingsResponse{} }
func (m *ListRatingsResponse) String() string { return proto.CompactTextString(m) }
func (*ListRatingsResponse) ProtoMessage()    {}
func (*ListRatingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8da69d9277c36882, []int{9}
}

func (m *ListRatingsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRatingsResponse.Unmarshal(m, b)
}
func (m *ListRatingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRatingsResponse.Marshal(b, m, deterministic)
}
func (m *ListRatingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRatingsResponse.Merge(m, src)
}
func (m *ListRatingsResponse) XXX_Size() int {
	return xxx_messageInfo_ListRatingsResponse.Size(m)
}
func (m *ListRatingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRatingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRatingsResponse proto.InternalMessageInfo

func (m *ListRatingsResponse) GetRatings() []*models.Rating {
	if m != nil {
		return m.Ratings
	}
	return nil
}

// DeckRequest is a request to get cards for decks
type DeckRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Decks                []string `protobuf:"bytes,2,rep,name=Decks,proto3" json:"Decks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeckRequest) Reset()         { *m = DeckRequest{} }
func (m *DeckRequest) String() string { return proto.CompactTextString(m) }
func (*DeckRequest) ProtoMessage()    {}
func (*DeckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8da69d9277c36882, []int{10}
}

func (m *DeckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeckRequest.Unmarshal(m, b)
}
func (m *DeckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeckRequest.Marshal(b, m, deterministic)
}
func (m *DeckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeckRequest.Merge(m, src)
}
func (m *DeckRequest) XXX_Size() int {
	return xxx_messageInfo_DeckRequest.Size(m)
}
func (m *DeckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeckRequest proto.InternalMessageInfo

func (m *DeckRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DeckRequest) GetDecks() []string {
	if m != nil {
		return m.Decks
	}
	return nil
}

// DeckContentResponse returns a list of cards for each decks in DeckRequest
type DeckContentResponse struct {
	DeckContents         []*DeckContent `protobuf:"bytes,1,rep,name=DeckContents,proto3" json:"DeckContents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DeckContentResponse) Reset()         { *m = DeckContentResponse{} }
func (m *DeckContentResponse) String() string { return proto.CompactTextString(m) }
func (*DeckContentResponse) ProtoMessage()    {}
func (*DeckContentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8da69d9277c36882, []int{11}
}

func (m *DeckContentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeckContentResponse.Unmarshal(m, b)
}
func (m *DeckContentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeckContentResponse.Marshal(b, m, deterministic)
}
func (m *DeckContentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeckContentResponse.Merge(m, src)
}
func (m *DeckContentResponse) XXX_Size() int {
	return xxx_messageInfo_DeckContentResponse.Size(m)
}
func (m *DeckContentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeckContentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeckContentResponse proto.InternalMessageInfo

func (m *DeckContentResponse) GetDeckContents() []*DeckContent {
	if m != nil {
		return m.DeckContents
	}
	return nil
}

// DeckContent contains a list of card references
type DeckContent struct {
	Name                 string           `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	CardRefs             []*CardReference `protobuf:"bytes,2,rep,name=CardRefs,proto3" json:"CardRefs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DeckContent) Reset()         { *m = DeckContent{} }
func (m *DeckContent) String() string { return proto.CompactTextString(m) }
func (*DeckContent) ProtoMessage()    {}
func (*DeckContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_8da69d9277c36882, []int{12}
}

func (m *DeckContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeckContent.Unmarshal(m, b)
}
func (m *DeckContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeckContent.Marshal(b, m, deterministic)
}
func (m *DeckContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeckContent.Merge(m, src)
}
func (m *DeckContent) XXX_Size() int {
	return xxx_messageInfo_DeckContent.Size(m)
}
func (m *DeckContent) XXX_DiscardUnknown() {
	xxx_messageInfo_DeckContent.DiscardUnknown(m)
}

var xxx_messageInfo_DeckContent proto.InternalMessageInfo

func (m *DeckContent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeckContent) GetCardRefs() []*CardReference {
	if m != nil {
		return m.CardRefs
	}
	return nil
}

// CardReference contains reference to an entity's type and ID
type CardReference struct {
	Type                 string   `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	ID                   string   `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CardReference) Reset()         { *m = CardReference{} }
func (m *CardReference) String() string { return proto.CompactTextString(m) }
func (*CardReference) ProtoMessage()    {}
func (*CardReference) Descriptor() ([]byte, []int) {
	return fileDescriptor_8da69d9277c36882, []int{13}
}

func (m *CardReference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardReference.Unmarshal(m, b)
}
func (m *CardReference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardReference.Marshal(b, m, deterministic)
}
func (m *CardReference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardReference.Merge(m, src)
}
func (m *CardReference) XXX_Size() int {
	return xxx_messageInfo_CardReference.Size(m)
}
func (m *CardReference) XXX_DiscardUnknown() {
	xxx_messageInfo_CardReference.DiscardUnknown(m)
}

var xxx_messageInfo_CardReference proto.InternalMessageInfo

func (m *CardReference) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CardReference) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func init() {
	proto.RegisterType((*GetByIDRequest)(nil), "data.GetByIDRequest")
	proto.RegisterType((*GetBySlugRequest)(nil), "data.GetBySlugRequest")
	proto.RegisterType((*ListRequest)(nil), "data.ListRequest")
	proto.RegisterType((*TimestampResponse)(nil), "data.TimestampResponse")
	proto.RegisterType((*FeedbackResponse)(nil), "data.FeedbackResponse")
	proto.RegisterType((*ListFeedbacksResponse)(nil), "data.ListFeedbacksResponse")
	proto.RegisterType((*VisitorResponse)(nil), "data.VisitorResponse")
	proto.RegisterType((*ListVisitorsResponse)(nil), "data.ListVisitorsResponse")
	proto.RegisterType((*RatingResponse)(nil), "data.RatingResponse")
	proto.RegisterType((*ListRatingsResponse)(nil), "data.ListRatingsResponse")
	proto.RegisterType((*DeckRequest)(nil), "data.DeckRequest")
	proto.RegisterType((*DeckContentResponse)(nil), "data.DeckContentResponse")
	proto.RegisterType((*DeckContent)(nil), "data.DeckContent")
	proto.RegisterType((*CardReference)(nil), "data.CardReference")
}

func init() { proto.RegisterFile("service_data.proto", fileDescriptor_8da69d9277c36882) }

var fileDescriptor_8da69d9277c36882 = []byte{
	// 644 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xdf, 0x4f, 0xd3, 0x50,
	0x14, 0x0e, 0x0c, 0x61, 0x9c, 0xb1, 0x31, 0x3a, 0xd0, 0x39, 0x1f, 0x24, 0xf7, 0x41, 0x67, 0xc4,
	0x36, 0x19, 0x62, 0x88, 0x48, 0x50, 0x58, 0x58, 0x88, 0x28, 0x49, 0x25, 0x3e, 0xf8, 0x62, 0xee,
	0xda, 0xb3, 0xd9, 0xb8, 0xb6, 0xb3, 0xf7, 0x8e, 0x84, 0xff, 0xd0, 0x3f, 0xcb, 0xdc, 0x9f, 0xed,
	0x56, 0xc0, 0xb7, 0x7b, 0xbe, 0xfb, 0x9d, 0xef, 0x9c, 0xd3, 0x7e, 0xe7, 0x82, 0xc3, 0x30, 0xbb,
	0x89, 0x02, 0xfc, 0x19, 0x52, 0x4e, 0xdd, 0x69, 0x96, 0xf2, 0xd4, 0x59, 0x11, 0xe7, 0xce, 0x46,
	0x9c, 0x86, 0x38, 0x61, 0x0a, 0xeb, 0xb4, 0x0c, 0x8f, 0x86, 0x71, 0x94, 0x68, 0xf0, 0xf9, 0x38,
	0x4d, 0xc7, 0x13, 0xf4, 0x64, 0x34, 0x9c, 0x8d, 0x3c, 0x1e, 0xc5, 0xc8, 0x38, 0x8d, 0xa7, 0x8a,
	0x40, 0x7a, 0xd0, 0x18, 0x20, 0x3f, 0xbd, 0xbd, 0xe8, 0xfb, 0xf8, 0x67, 0x86, 0x8c, 0x3b, 0x4d,
	0xa8, 0x7c, 0xc6, 0xdb, 0xf6, 0xd2, 0xee, 0x52, 0x77, 0xdd, 0x17, 0x47, 0xa7, 0x01, 0xcb, 0x17,
	0xfd, 0xf6, 0xb2, 0x04, 0x96, 0x2f, 0xfa, 0xe4, 0x10, 0x9a, 0x32, 0xe7, 0xdb, 0x64, 0x36, 0xbe,
	0x3f, 0xcb, 0x81, 0x15, 0x41, 0xd0, 0x79, 0xf2, 0x4c, 0x6e, 0xa0, 0x76, 0x19, 0x31, 0x7e, 0x7f,
	0xd2, 0x1e, 0x54, 0x05, 0xe1, 0x6a, 0xca, 0x99, 0x4c, 0xac, 0xf5, 0x9a, 0xae, 0x9e, 0xd2, 0xe0,
	0xbe, 0x65, 0x38, 0x2f, 0x61, 0xed, 0x3c, 0x9a, 0x70, 0xcc, 0x58, 0xbb, 0xb2, 0x5b, 0xe9, 0xd6,
	0x7a, 0x75, 0x57, 0x0d, 0xaf, 0x50, 0xdf, 0xdc, 0x92, 0x2b, 0xd8, 0xba, 0x36, 0x83, 0xfb, 0xc8,
	0xa6, 0x69, 0xc2, 0xd0, 0x79, 0x0f, 0xf0, 0x25, 0x0d, 0xa3, 0x51, 0x84, 0xe1, 0x27, 0x2e, 0x9b,
	0xa8, 0xf5, 0x3a, 0xae, 0xfa, 0x60, 0xae, 0xf9, 0x60, 0x6e, 0x9e, 0x57, 0x60, 0x93, 0x8f, 0xd0,
	0x3c, 0x47, 0x0c, 0x87, 0x34, 0xf8, 0x6d, 0xf5, 0xf6, 0xa0, 0x6a, 0x30, 0xad, 0x66, 0x7b, 0xb7,
	0x5c, 0xcb, 0x20, 0x03, 0xd8, 0x11, 0x73, 0x98, 0x98, 0x59, 0x19, 0x17, 0xd6, 0x2d, 0xd8, 0x5e,
	0x92, 0x63, 0x95, 0x75, 0x72, 0x0a, 0xf9, 0x00, 0x9b, 0xdf, 0x23, 0x16, 0xf1, 0x34, 0xb3, 0x12,
	0xaf, 0x60, 0x4d, 0x43, 0xba, 0x91, 0x4d, 0x23, 0x60, 0x98, 0xe6, 0x9e, 0x9c, 0xc1, 0xb6, 0x68,
	0x43, 0x87, 0x79, 0x17, 0xaf, 0xa1, 0x6a, 0x30, 0xdd, 0x44, 0x49, 0xc3, 0x12, 0xc8, 0x21, 0x34,
	0x7c, 0xca, 0xa3, 0x64, 0x6c, 0xd3, 0x5f, 0xc0, 0xaa, 0x42, 0x74, 0x03, 0x0d, 0x93, 0xac, 0x79,
	0xfa, 0x96, 0x9c, 0x40, 0x4b, 0x1a, 0x42, 0x46, 0x79, 0xf5, 0x2e, 0xac, 0x69, 0x48, 0x17, 0x5f,
	0xcc, 0x37, 0xd7, 0xe4, 0x00, 0x6a, 0x7d, 0x14, 0x3f, 0xe1, 0x3e, 0x47, 0x6d, 0xc3, 0x23, 0x41,
	0x10, 0x76, 0xaa, 0x74, 0xd7, 0x7d, 0x15, 0x90, 0x4b, 0x68, 0x89, 0xc3, 0x59, 0x9a, 0x70, 0x4c,
	0xb8, 0xad, 0x7b, 0x00, 0x1b, 0x05, 0xd8, 0x14, 0xdf, 0x72, 0xe5, 0xea, 0x15, 0x13, 0xe6, 0x68,
	0xc4, 0x57, 0x4d, 0xe8, 0x58, 0x38, 0xff, 0x2b, 0x8d, 0x51, 0x77, 0x21, 0xcf, 0x8e, 0x07, 0xd5,
	0x33, 0x9a, 0x85, 0x3e, 0x8e, 0x54, 0x27, 0xb5, 0x5e, 0x4b, 0xa9, 0x6a, 0x14, 0x33, 0x4c, 0x02,
	0xf4, 0x2d, 0x89, 0xec, 0x43, 0x7d, 0xee, 0x4a, 0xa8, 0x5e, 0xdf, 0x4e, 0xad, 0xaa, 0x38, 0x2f,
	0x6e, 0x66, 0xef, 0x6f, 0x05, 0x56, 0xfa, 0x94, 0x53, 0xe7, 0x04, 0x36, 0x07, 0x68, 0xcd, 0x25,
	0xd6, 0xdb, 0xd9, 0x56, 0xf5, 0xe6, 0xb7, 0xbd, 0xf3, 0x58, 0xa1, 0x25, 0x33, 0x9f, 0x40, 0x7d,
	0xce, 0x9e, 0x8e, 0xfe, 0x08, 0x85, 0xf5, 0xed, 0x3c, 0xcb, 0xa1, 0xb2, 0x8d, 0x8f, 0xe5, 0xc3,
	0xa2, 0x2d, 0xf2, 0x40, 0x03, 0x3b, 0x0a, 0x5d, 0xb4, 0xf0, 0x31, 0x6c, 0x14, 0x7d, 0x79, 0x57,
	0xf9, 0x4e, 0x0e, 0x95, 0xec, 0x7b, 0x04, 0xf5, 0x01, 0x6a, 0x5b, 0x3d, 0x50, 0x5c, 0xa3, 0x0b,
	0xe6, 0x3d, 0x87, 0x9d, 0x01, 0x72, 0xb3, 0xed, 0xff, 0x15, 0x79, 0xa2, 0xd0, 0xf2, 0x03, 0x73,
	0xa4, 0x5f, 0x3b, 0x65, 0xd5, 0xbb, 0x46, 0x78, 0x5a, 0x80, 0xe6, 0x57, 0xe0, 0xf4, 0xdd, 0x8f,
	0xb7, 0xe3, 0x88, 0xff, 0x9a, 0x0d, 0xdd, 0x20, 0x8d, 0xbd, 0x98, 0x05, 0x19, 0x1d, 0x71, 0x16,
	0xd3, 0xc4, 0x0b, 0xf1, 0x26, 0x48, 0x93, 0x37, 0x23, 0xfd, 0xc9, 0x3d, 0xfd, 0xee, 0x33, 0x4f,
	0x68, 0x0d, 0x57, 0xe5, 0xcb, 0xb5, 0xff, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x75, 0xdc, 0xc6,
	0x37, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DataClient is the client API for Data service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataClient interface {
	// GetFeedbackByID returns a single Feedback from database by primary key
	GetFeedbackByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*FeedbackResponse, error)
	// ListFeedbacks allows listing all entity of type Feedback
	ListFeedbacks(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListFeedbacksResponse, error)
	// GetVisitorByID returns a single Visitor from database by primary key
	GetVisitorByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*VisitorResponse, error)
	// ListVisitors allows listing all entity of type Visitor
	ListVisitors(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListVisitorsResponse, error)
	// GetRatingByID returns a single Rating from database by primary key
	GetRatingByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*RatingResponse, error)
	GetModifiedRatingByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*TimestampResponse, error)
	// ListRatings allows listing all entity of type Rating
	ListRatings(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListRatingsResponse, error)
}

type dataClient struct {
	cc *grpc.ClientConn
}

func NewDataClient(cc *grpc.ClientConn) DataClient {
	return &dataClient{cc}
}

func (c *dataClient) GetFeedbackByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*FeedbackResponse, error) {
	out := new(FeedbackResponse)
	err := c.cc.Invoke(ctx, "/data.Data/GetFeedbackByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataClient) ListFeedbacks(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListFeedbacksResponse, error) {
	out := new(ListFeedbacksResponse)
	err := c.cc.Invoke(ctx, "/data.Data/ListFeedbacks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataClient) GetVisitorByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*VisitorResponse, error) {
	out := new(VisitorResponse)
	err := c.cc.Invoke(ctx, "/data.Data/GetVisitorByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataClient) ListVisitors(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListVisitorsResponse, error) {
	out := new(ListVisitorsResponse)
	err := c.cc.Invoke(ctx, "/data.Data/ListVisitors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataClient) GetRatingByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*RatingResponse, error) {
	out := new(RatingResponse)
	err := c.cc.Invoke(ctx, "/data.Data/GetRatingByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataClient) GetModifiedRatingByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*TimestampResponse, error) {
	out := new(TimestampResponse)
	err := c.cc.Invoke(ctx, "/data.Data/GetModifiedRatingByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataClient) ListRatings(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListRatingsResponse, error) {
	out := new(ListRatingsResponse)
	err := c.cc.Invoke(ctx, "/data.Data/ListRatings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataServer is the server API for Data service.
type DataServer interface {
	// GetFeedbackByID returns a single Feedback from database by primary key
	GetFeedbackByID(context.Context, *GetByIDRequest) (*FeedbackResponse, error)
	// ListFeedbacks allows listing all entity of type Feedback
	ListFeedbacks(context.Context, *ListRequest) (*ListFeedbacksResponse, error)
	// GetVisitorByID returns a single Visitor from database by primary key
	GetVisitorByID(context.Context, *GetByIDRequest) (*VisitorResponse, error)
	// ListVisitors allows listing all entity of type Visitor
	ListVisitors(context.Context, *ListRequest) (*ListVisitorsResponse, error)
	// GetRatingByID returns a single Rating from database by primary key
	GetRatingByID(context.Context, *GetByIDRequest) (*RatingResponse, error)
	GetModifiedRatingByID(context.Context, *GetByIDRequest) (*TimestampResponse, error)
	// ListRatings allows listing all entity of type Rating
	ListRatings(context.Context, *ListRequest) (*ListRatingsResponse, error)
}

func RegisterDataServer(s *grpc.Server, srv DataServer) {
	s.RegisterService(&_Data_serviceDesc, srv)
}

func _Data_GetFeedbackByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).GetFeedbackByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.Data/GetFeedbackByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).GetFeedbackByID(ctx, req.(*GetByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Data_ListFeedbacks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).ListFeedbacks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.Data/ListFeedbacks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).ListFeedbacks(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Data_GetVisitorByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).GetVisitorByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.Data/GetVisitorByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).GetVisitorByID(ctx, req.(*GetByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Data_ListVisitors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).ListVisitors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.Data/ListVisitors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).ListVisitors(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Data_GetRatingByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).GetRatingByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.Data/GetRatingByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).GetRatingByID(ctx, req.(*GetByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Data_GetModifiedRatingByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).GetModifiedRatingByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.Data/GetModifiedRatingByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).GetModifiedRatingByID(ctx, req.(*GetByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Data_ListRatings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).ListRatings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.Data/ListRatings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).ListRatings(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Data_serviceDesc = grpc.ServiceDesc{
	ServiceName: "data.Data",
	HandlerType: (*DataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFeedbackByID",
			Handler:    _Data_GetFeedbackByID_Handler,
		},
		{
			MethodName: "ListFeedbacks",
			Handler:    _Data_ListFeedbacks_Handler,
		},
		{
			MethodName: "GetVisitorByID",
			Handler:    _Data_GetVisitorByID_Handler,
		},
		{
			MethodName: "ListVisitors",
			Handler:    _Data_ListVisitors_Handler,
		},
		{
			MethodName: "GetRatingByID",
			Handler:    _Data_GetRatingByID_Handler,
		},
		{
			MethodName: "GetModifiedRatingByID",
			Handler:    _Data_GetModifiedRatingByID_Handler,
		},
		{
			MethodName: "ListRatings",
			Handler:    _Data_ListRatings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_data.proto",
}
