// generated by gocipe ce0bfb5c18c811c9714539fbe97b8d7b2dff895a3a2978a083ddc4f23c0a35ab; DO NOT EDIT

package models

//ListFilter represents a filter to apply during listing (crud)
type ListFilter struct {
	Field     string
	Operation string
	Value     interface{}
}
