// generated by gocipe 7024126c5667f01762364d56ce1e35bbbebe5543247abb9a7edcb6ee359cef12; DO NOT EDIT

package models

//ListFilter represents a filter to apply during listing (crud)
type ListFilter struct {
	Field     string
	Operation string
	Value     interface{}
}
