// generated by gocipe 98d04eff905d6c25e0ba7946b5abe59ef772bba989a56cb131b63b92b50cf33b; DO NOT EDIT

package models

//ListFilter represents a filter to apply during listing (crud)
type ListFilter struct {
	Field     string
	Operation string
	Value     interface{}
}
