// generated by gocipe a113b3c3d9f0bc69a9636981154d6293fbd50d8eed8462b35778873cde989dae; DO NOT EDIT

package models

//ListFilter represents a filter to apply during listing (crud)
type ListFilter struct {
	Field     string
	Operation string
	Value     interface{}
}
