// Code generated by protoc-gen-go. DO NOT EDIT.
// source: models.proto

package models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ListOpts contains options for listing, including Offset, Limit and Sort
type ListOpts struct {
	Offset               int64           `protobuf:"varint,1,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Limit                int64           `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Sort                 []*ListSortOpts `protobuf:"bytes,3,rep,name=Sort,proto3" json:"Sort,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListOpts) Reset()         { *m = ListOpts{} }
func (m *ListOpts) String() string { return proto.CompactTextString(m) }
func (*ListOpts) ProtoMessage()    {}
func (*ListOpts) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{0}
}

func (m *ListOpts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOpts.Unmarshal(m, b)
}
func (m *ListOpts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOpts.Marshal(b, m, deterministic)
}
func (m *ListOpts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOpts.Merge(m, src)
}
func (m *ListOpts) XXX_Size() int {
	return xxx_messageInfo_ListOpts.Size(m)
}
func (m *ListOpts) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOpts.DiscardUnknown(m)
}

var xxx_messageInfo_ListOpts proto.InternalMessageInfo

func (m *ListOpts) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListOpts) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListOpts) GetSort() []*ListSortOpts {
	if m != nil {
		return m.Sort
	}
	return nil
}

type ListSortOpts struct {
	Field                string   `protobuf:"bytes,1,opt,name=Field,proto3" json:"Field,omitempty"`
	Ascending            bool     `protobuf:"varint,2,opt,name=Ascending,proto3" json:"Ascending,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSortOpts) Reset()         { *m = ListSortOpts{} }
func (m *ListSortOpts) String() string { return proto.CompactTextString(m) }
func (*ListSortOpts) ProtoMessage()    {}
func (*ListSortOpts) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{1}
}

func (m *ListSortOpts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSortOpts.Unmarshal(m, b)
}
func (m *ListSortOpts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSortOpts.Marshal(b, m, deterministic)
}
func (m *ListSortOpts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSortOpts.Merge(m, src)
}
func (m *ListSortOpts) XXX_Size() int {
	return xxx_messageInfo_ListSortOpts.Size(m)
}
func (m *ListSortOpts) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSortOpts.DiscardUnknown(m)
}

var xxx_messageInfo_ListSortOpts proto.InternalMessageInfo

func (m *ListSortOpts) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *ListSortOpts) GetAscending() bool {
	if m != nil {
		return m.Ascending
	}
	return false
}

// Feedback A Feedback
type Feedback struct {
	ID                   string               `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Status               string               `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	UserID               string               `protobuf:"bytes,3,opt,name=UserID,proto3" json:"UserID,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	SessionID            string               `protobuf:"bytes,5,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	Reaction1            string               `protobuf:"bytes,6,opt,name=Reaction1,proto3" json:"Reaction1,omitempty"`
	Reaction2            string               `protobuf:"bytes,7,opt,name=Reaction2,proto3" json:"Reaction2,omitempty"`
	Reaction3            string               `protobuf:"bytes,8,opt,name=Reaction3,proto3" json:"Reaction3,omitempty"`
	Reaction4            string               `protobuf:"bytes,9,opt,name=Reaction4,proto3" json:"Reaction4,omitempty"`
	VisitorID            string               `protobuf:"bytes,10,opt,name=VisitorID,proto3" json:"VisitorID,omitempty"`
	Visitor              *Visitor             `protobuf:"bytes,11,opt,name=Visitor,proto3" json:"Visitor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Feedback) Reset()         { *m = Feedback{} }
func (m *Feedback) String() string { return proto.CompactTextString(m) }
func (*Feedback) ProtoMessage()    {}
func (*Feedback) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{2}
}

func (m *Feedback) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Feedback.Unmarshal(m, b)
}
func (m *Feedback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Feedback.Marshal(b, m, deterministic)
}
func (m *Feedback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feedback.Merge(m, src)
}
func (m *Feedback) XXX_Size() int {
	return xxx_messageInfo_Feedback.Size(m)
}
func (m *Feedback) XXX_DiscardUnknown() {
	xxx_messageInfo_Feedback.DiscardUnknown(m)
}

var xxx_messageInfo_Feedback proto.InternalMessageInfo

func (m *Feedback) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Feedback) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Feedback) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Feedback) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Feedback) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *Feedback) GetReaction1() string {
	if m != nil {
		return m.Reaction1
	}
	return ""
}

func (m *Feedback) GetReaction2() string {
	if m != nil {
		return m.Reaction2
	}
	return ""
}

func (m *Feedback) GetReaction3() string {
	if m != nil {
		return m.Reaction3
	}
	return ""
}

func (m *Feedback) GetReaction4() string {
	if m != nil {
		return m.Reaction4
	}
	return ""
}

func (m *Feedback) GetVisitorID() string {
	if m != nil {
		return m.VisitorID
	}
	return ""
}

func (m *Feedback) GetVisitor() *Visitor {
	if m != nil {
		return m.Visitor
	}
	return nil
}

// Visitor A visitor
type Visitor struct {
	ID                   string               `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Status               string               `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	UserID               string               `protobuf:"bytes,3,opt,name=UserID,proto3" json:"UserID,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	Name                 string               `protobuf:"bytes,5,opt,name=Name,proto3" json:"Name,omitempty"`
	Bookmark             string               `protobuf:"bytes,6,opt,name=Bookmark,proto3" json:"Bookmark,omitempty"`
	PhotoLink            string               `protobuf:"bytes,7,opt,name=PhotoLink,proto3" json:"PhotoLink,omitempty"`
	Feedbacks            []*Feedback          `protobuf:"bytes,8,rep,name=Feedbacks,proto3" json:"Feedbacks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Visitor) Reset()         { *m = Visitor{} }
func (m *Visitor) String() string { return proto.CompactTextString(m) }
func (*Visitor) ProtoMessage()    {}
func (*Visitor) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{3}
}

func (m *Visitor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Visitor.Unmarshal(m, b)
}
func (m *Visitor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Visitor.Marshal(b, m, deterministic)
}
func (m *Visitor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Visitor.Merge(m, src)
}
func (m *Visitor) XXX_Size() int {
	return xxx_messageInfo_Visitor.Size(m)
}
func (m *Visitor) XXX_DiscardUnknown() {
	xxx_messageInfo_Visitor.DiscardUnknown(m)
}

var xxx_messageInfo_Visitor proto.InternalMessageInfo

func (m *Visitor) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Visitor) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Visitor) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Visitor) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Visitor) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Visitor) GetBookmark() string {
	if m != nil {
		return m.Bookmark
	}
	return ""
}

func (m *Visitor) GetPhotoLink() string {
	if m != nil {
		return m.PhotoLink
	}
	return ""
}

func (m *Visitor) GetFeedbacks() []*Feedback {
	if m != nil {
		return m.Feedbacks
	}
	return nil
}

// Rating A rating
type Rating struct {
	ID                   string               `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Status               string               `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	UserID               string               `protobuf:"bytes,3,opt,name=UserID,proto3" json:"UserID,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	RatingCount          string               `protobuf:"bytes,6,opt,name=RatingCount,proto3" json:"RatingCount,omitempty"`
	Score                int64                `protobuf:"varint,7,opt,name=Score,proto3" json:"Score,omitempty"`
	ReactionSummary      string               `protobuf:"bytes,8,opt,name=ReactionSummary,proto3" json:"ReactionSummary,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Rating) Reset()         { *m = Rating{} }
func (m *Rating) String() string { return proto.CompactTextString(m) }
func (*Rating) ProtoMessage()    {}
func (*Rating) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{4}
}

func (m *Rating) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rating.Unmarshal(m, b)
}
func (m *Rating) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rating.Marshal(b, m, deterministic)
}
func (m *Rating) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rating.Merge(m, src)
}
func (m *Rating) XXX_Size() int {
	return xxx_messageInfo_Rating.Size(m)
}
func (m *Rating) XXX_DiscardUnknown() {
	xxx_messageInfo_Rating.DiscardUnknown(m)
}

var xxx_messageInfo_Rating proto.InternalMessageInfo

func (m *Rating) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Rating) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Rating) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Rating) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Rating) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Rating) GetRatingCount() string {
	if m != nil {
		return m.RatingCount
	}
	return ""
}

func (m *Rating) GetScore() int64 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *Rating) GetReactionSummary() string {
	if m != nil {
		return m.ReactionSummary
	}
	return ""
}

func init() {
	proto.RegisterType((*ListOpts)(nil), "models.ListOpts")
	proto.RegisterType((*ListSortOpts)(nil), "models.ListSortOpts")
	proto.RegisterType((*Feedback)(nil), "models.Feedback")
	proto.RegisterType((*Visitor)(nil), "models.Visitor")
	proto.RegisterType((*Rating)(nil), "models.Rating")
}

func init() { proto.RegisterFile("models.proto", fileDescriptor_0b5431a010549573) }

var fileDescriptor_0b5431a010549573 = []byte{
	// 500 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x93, 0x4f, 0x6b, 0xdb, 0x30,
	0x18, 0xc6, 0x89, 0xf3, 0xa7, 0xb6, 0x52, 0xd6, 0x21, 0xca, 0x10, 0x61, 0xb0, 0x90, 0x93, 0x77,
	0xa8, 0xcd, 0x92, 0x1e, 0x7a, 0x6d, 0x1a, 0x0a, 0x81, 0xb0, 0x0e, 0x79, 0xdd, 0x61, 0x37, 0xd9,
	0x96, 0x5d, 0x91, 0xc8, 0x0a, 0x96, 0x3c, 0xd8, 0x71, 0x5f, 0x64, 0x5f, 0x6e, 0x5f, 0x64, 0xe8,
	0x8f, 0x1d, 0x67, 0x97, 0x1d, 0x7b, 0xcb, 0xf3, 0x7b, 0x5e, 0xbd, 0x7a, 0xf5, 0xe4, 0x35, 0xb8,
	0xe4, 0x22, 0xa7, 0x07, 0x19, 0x1d, 0x6b, 0xa1, 0x04, 0x9c, 0x58, 0x35, 0xfb, 0x50, 0x0a, 0x51,
	0x1e, 0x68, 0x6c, 0x68, 0xda, 0x14, 0xb1, 0x62, 0x9c, 0x4a, 0x45, 0xf8, 0xd1, 0x16, 0x2e, 0x52,
	0xe0, 0xef, 0x98, 0x54, 0x4f, 0x47, 0x25, 0xe1, 0x3b, 0x30, 0x79, 0x2a, 0x0a, 0x49, 0x15, 0x1a,
	0xcc, 0x07, 0xe1, 0x10, 0x3b, 0x05, 0xaf, 0xc1, 0x78, 0xc7, 0x38, 0x53, 0xc8, 0x33, 0xd8, 0x0a,
	0x18, 0x82, 0x51, 0x22, 0x6a, 0x85, 0x86, 0xf3, 0x61, 0x38, 0x5d, 0x5e, 0x47, 0xee, 0x7e, 0xdd,
	0x4d, 0x73, 0xdd, 0x11, 0x9b, 0x8a, 0xc5, 0x1a, 0x5c, 0xf6, 0xa9, 0xee, 0xf7, 0xc8, 0xe8, 0x21,
	0x37, 0xd7, 0x04, 0xd8, 0x0a, 0xf8, 0x1e, 0x04, 0xf7, 0x32, 0xa3, 0x55, 0xce, 0xaa, 0xd2, 0xdc,
	0xe4, 0xe3, 0x13, 0x58, 0xfc, 0xf1, 0x80, 0xff, 0x48, 0x69, 0x9e, 0x92, 0x6c, 0x0f, 0xdf, 0x00,
	0x6f, 0xbb, 0x71, 0xa7, 0xbd, 0xed, 0x46, 0x0f, 0x9e, 0x28, 0xa2, 0x1a, 0x69, 0xce, 0x05, 0xd8,
	0x29, 0xcd, 0x9f, 0x25, 0xad, 0xb7, 0x1b, 0x34, 0xb4, 0xdc, 0x2a, 0x78, 0x07, 0x82, 0x87, 0x9a,
	0x12, 0x45, 0xf3, 0x7b, 0x85, 0x46, 0xf3, 0x41, 0x38, 0x5d, 0xce, 0x22, 0x9b, 0x54, 0xd4, 0x26,
	0x15, 0x7d, 0x6d, 0x93, 0xc2, 0xa7, 0x62, 0x3d, 0x64, 0x42, 0xa5, 0x64, 0xa2, 0xda, 0x6e, 0xd0,
	0xd8, 0x34, 0x3d, 0x01, 0xed, 0x62, 0x4a, 0x32, 0xc5, 0x44, 0xf5, 0x09, 0x4d, 0xac, 0xdb, 0x81,
	0xbe, 0xbb, 0x44, 0x17, 0xe7, 0xee, 0xb2, 0xef, 0xae, 0x90, 0x7f, 0xee, 0xae, 0xfa, 0xee, 0x2d,
	0x0a, 0xce, 0xdd, 0x5b, 0xed, 0x7e, 0x63, 0x92, 0x29, 0xa1, 0x9f, 0x0a, 0xac, 0xdb, 0x01, 0xf8,
	0x11, 0x5c, 0x38, 0x81, 0xa6, 0xe6, 0xad, 0x57, 0xed, 0x7f, 0xe5, 0x30, 0x6e, 0xfd, 0xc5, 0x2f,
	0xaf, 0xab, 0x7d, 0xc5, 0x90, 0x21, 0x18, 0x7d, 0x26, 0x9c, 0xba, 0x7c, 0xcd, 0x6f, 0x38, 0x03,
	0xfe, 0x5a, 0x88, 0x3d, 0x27, 0xf5, 0xde, 0x25, 0xdb, 0x69, 0xfd, 0xfc, 0x2f, 0x2f, 0x42, 0x89,
	0x1d, 0xab, 0xf6, 0x6d, 0xb0, 0x1d, 0x80, 0x11, 0x08, 0xda, 0xc5, 0x91, 0xc8, 0x37, 0xcb, 0xfa,
	0xb6, 0x0d, 0xa0, 0x35, 0xf0, 0xa9, 0x64, 0xf1, 0xdb, 0x03, 0x13, 0x4c, 0x14, 0xab, 0xca, 0x57,
	0x8c, 0xe0, 0x0e, 0x04, 0xcf, 0xc7, 0xdc, 0x9d, 0x1c, 0xff, 0xff, 0x64, 0x57, 0x0c, 0xe7, 0x60,
	0x6a, 0xa7, 0x7f, 0x10, 0x4d, 0xa5, 0x5c, 0x56, 0x7d, 0xa4, 0x3f, 0xbf, 0x24, 0x13, 0x35, 0x35,
	0x51, 0x0d, 0xb1, 0x15, 0x30, 0x04, 0x57, 0xed, 0x42, 0x25, 0x0d, 0xe7, 0xa4, 0xfe, 0xe9, 0xb6,
	0xf0, 0x5f, 0xbc, 0x8e, 0xbf, 0xdf, 0x94, 0x4c, 0xbd, 0x34, 0x69, 0x94, 0x09, 0x1e, 0x73, 0x99,
	0xd5, 0xa4, 0x50, 0x92, 0x93, 0x2a, 0xce, 0xe9, 0x8f, 0x4c, 0x54, 0x37, 0x85, 0xcb, 0x32, 0xb6,
	0x29, 0xa7, 0x13, 0x33, 0xf1, 0xea, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6f, 0x2b, 0x47, 0x3b,
	0xa3, 0x04, 0x00, 0x00,
}
